/**
 * Modules 4, 5 and 6: combining peptides, what to expect and staying safe,
 * and keeping up. Written for beginners, in the same plain voice as the rest
 * of the course, and on the same line: reported practice and published
 * evidence explained to an audience, never a plan for one person.
 */

export const MODULE_4 = {
  n: 4,
  slug: "stacking",
  title: "Combining peptides",
  summary: "Why you change one thing at a time, which peptides pair well and why, which clash, and how cycling really works.",
  status: "ready",
  lessons: [
    {
      slug: "one-variable",
      title: "One thing at a time",
      minutes: 8,
      free: false,
      summary: "Why starting three peptides at once teaches you nothing, and the order careful people use instead.",
      body: [
        { t: "p", text: "The most common way beginners waste money in this market isn't buying a bad vial. It's starting three peptides in the same week, feeling different a month later, and having no idea which one did it, or whether any of them did. A stack built that way can never be improved, because nothing in it can be tested." },
        { t: "h", text: "The rule" },
        { t: "p", text: "One new thing at a time, kept long enough to judge, with everything else held steady. For most peptides that means two to four weeks before the next change. For the growth hormone group and the weight-loss peptides, whose effects build over months, it means longer. The log from module two is what makes the judgment possible." },
        { t: "fig", id: "one-variable", caption: "The difference between an experiment and a guess." },
        { t: "h", text: "The order experienced people tend to follow" },
        { t: "steps", items: [
          "The peptide with the clearest evidence for the actual problem, on its own. If the problem is a sore tendon, that's a recovery peptide, not a growth hormone stack that might also help.",
          "Started at a low reported dose, then raised if nothing happens. Not started high and lowered after side effects.",
          "A second peptide only after the first has been judged: kept because it helped, or dropped because it didn't. Never added to rescue a first peptide that isn't working.",
          "Blends last, and only from peptides you've already run separately. A blend is a conclusion, not a starting point.",
        ] },
        { t: "h", text: "Everything else held steady" },
        { t: "p", text: "A new training program, a diet change, a new supplement, a change in sleep: any of these produces effects as big as most peptides do. If one of them changes in the same window, the log can't separate them. It's boring, and it's the only way to end up knowing what works for you instead of believing it." },
        { t: "note", text: "The question that sorts this out fast: if this peptide did nothing, would I be able to tell? If the answer is no, the stack isn't ready for it." },
      ],
    },
    {
      slug: "what-pairs",
      title: "What pairs well, and why",
      minutes: 14,
      free: false,
      summary: "The common stacks explained: the reasoning behind each pairing, and the honest amount of evidence for it.",
      body: [
        { t: "p", text: "A pairing makes sense when two peptides work in different ways on the same goal, or when one covers a weakness of the other. Most blends sold in this market pass the first test. Almost none have evidence for the combination itself, so what follows is the reasoning behind each one, not a finding." },
        { t: "h", text: "A releasing peptide plus ipamorelin" },
        { t: "p", text: "The one pairing with real pharmacology behind it. A releasing peptide (CJC-1295 or tesamorelin) makes each growth hormone burst bigger, and ipamorelin triggers a burst while quieting the hormone that would blunt it. Together they produce a bigger burst than either alone, in human studies of the individual pieces. CJC-1295 without DAC plus ipamorelin is the standard version. Tesamorelin plus ipamorelin is the expensive one. Taken together, before bed, on an empty stomach." },
        { t: "h", text: "BPC-157 plus TB-500" },
        { t: "p", text: "The recovery pairing, sold as Wolverine. The logic is that they work differently: one on blood vessels and local signals, the other on cell movement and inflammation. Each has animal evidence alone and neither has human evidence together. Because their normal schedules differ, a blend compromises one of them, and people who run them separately usually take BPC-157 daily and TB-500 twice a week." },
        { t: "h", text: "A weight-loss peptide plus a growth hormone peptide" },
        { t: "p", text: "The most-discussed pairing among people on semaglutide or tirzepatide, aimed at the muscle loss those drugs cause. The reasoning is that growth hormone helps hold on to muscle while losing weight. There's no trial of the combination, and the two push blood sugar in opposite directions, which is either a balance or a mess depending on the person. The version of this pairing that actually has evidence is lifting weights and eating enough protein." },
        { t: "h", text: "GHK-Cu plus a recovery peptide" },
        { t: "p", text: "The Glow blend. Collagen production alongside tissue repair, for skin and healing together. Makes sense as a mechanism, unstudied as a combination, and complicated by GHK-Cu's injection sting, which makes people quit the whole blend over a side effect that belongs to one part of it." },
        { t: "h", text: "Selank plus semax" },
        { t: "p", text: "A common pairing among nasal-spray users: one for calm, one for drive. They come from the same Russian research program and were sometimes studied together there. People describe the combination as focus without edge. Since both are short-acting and taken as needed, they're also easy to try separately first, which is what the one-thing-at-a-time rule asks." },
        { t: "h", text: "Thymosin alpha-1 alongside almost anything" },
        { t: "p", text: "Less a pairing than a background. Because its safety record is long and it works on the immune system rather than any of the other systems, it's the peptide most often run alongside others without muddying the picture." },
        { t: "note", text: "Every pairing above is better as two vials than as one blend, because two vials can be dosed on their own schedules and dropped one at a time. Blends are for people who already know the pairing works for them and want the convenience." },
      ],
    },
    {
      slug: "what-conflicts",
      title: "What clashes",
      minutes: 10,
      free: false,
      summary: "Peptides that push the same system twice, share a side effect, or make each other impossible to judge.",
      body: [
        { t: "p", text: "Clashes in this market are rarely dangerous chemistry. They're two peptides pushing the same body system, two peptides sharing a side effect, or two peptides that make each other unreadable in your log." },
        { t: "h", text: "Pushing the same system twice" },
        { t: "list", items: [
          "Two releasing peptides together, or a releasing peptide plus synthetic growth hormone. The pituitary can only release what it has, and adding synthetic growth hormone on top defeats the whole reason people chose the peptide route.",
          "Two weight-loss peptides. Nobody plans this, but people switching from semaglutide to tirzepatide sometimes overlap them, and both stay in the body for a week or more. Switching means stopping one and waiting.",
          "Melanotan 2 plus PT-141. Same family of receptors, and PT-141 was made from melanotan 2. Stacking them doubles the nausea and the blood-pressure effect for no extra benefit.",
        ] },
        { t: "h", text: "Side effects that add up" },
        { t: "list", items: [
          "Blood sugar: growth hormone peptides push it up, weight-loss peptides push it down, and stimulant-type brain peptides can go either way. Together it's a moving target only bloodwork can read.",
          "Blood pressure: semax, PT-141, melanotan 2 and high-dose NAD+ can each raise or shift it. Together, in someone already borderline, that's a problem.",
          "Nausea: the weight-loss peptides, PT-141, melanotan 2 and fast NAD+ all cause it. Two at once is often why someone decides a peptide is unbearable when it was the pairing.",
          "Water retention and achy joints: the growth hormone group, and less predictably the recovery peptides. Together they're the usual explanation for puffy hands.",
        ] },
        { t: "h", text: "Combinations that make each other unreadable" },
        { t: "p", text: "Two peptides started together for the same goal, whatever they are. The clash isn't in the body, it's in the log. And any peptide started in the same two weeks as a new medication, because the medication's side effects will get blamed on the peptide or the other way round." },
        { t: "h", text: "With medications" },
        { t: "p", text: "The overlaps that matter are covered in module five. The short list: anything that lowers blood sugar with the weight-loss or growth hormone peptides; anything for blood pressure with the tanning and desire peptides and semax; sedatives with selank; blood thinners with anything that affects blood vessels, which on theory includes several recovery peptides." },
        { t: "warn", text: "None of these clashes has been studied in a trial, because no trial has tested the combinations. That cuts both ways. No documented clash is not the same as safe." },
      ],
    },
    {
      slug: "cycling",
      title: "Cycling and timing",
      minutes: 10,
      free: false,
      summary: "On and off periods as people practise them, why some peptides need breaks and some don't, and when in the day each is taken.",
      body: [
        { t: "p", text: "Cycling means taking a peptide for a while and then stopping for a while. People do it for three different reasons that get mixed up with each other. Knowing which reason applies to a peptide tells you whether a break is biology or superstition." },
        { t: "h", text: "Reason one: the body adapts" },
        { t: "p", text: "Keep pressing the same switch and the switch gets less sensitive. The growth hormone peptides are the clearest case: continuous use produces smaller bursts over time, and breaks restore them. Selank and semax users report tolerance with daily use. Here the break has a real mechanism. A typical pattern is eight to twelve weeks on and four off for the growth hormone group, and days rather than weeks for the nasal brain peptides." },
        { t: "h", text: "Reason two: the job is done" },
        { t: "p", text: "Recovery peptides are run for the length of an injury. Thymosin alpha-1 is run through an illness or a season. Melanotan is run until the tan is where someone wants it. There's no reason to continue past the goal, and the \"break\" is just stopping." },
        { t: "h", text: "Reason three: nobody knows" },
        { t: "p", text: "The longevity peptides and the Russian bioregulators are cycled in short courses with long gaps because that's how their original protocols ran, and because taking an unstudied compound for limited periods is the cautious default. The break is caution, not evidence. It's still the right default." },
        { t: "h", text: "The peptides where cycling isn't the point" },
        { t: "list", items: [
          "The weight-loss peptides are long-term drugs. Stopping brings appetite back and, in the trials, most of the weight within a year. A break is a decision to stop, made with that understood.",
          "Tesamorelin at its approved use is continuous. Cycling it is a habit borrowed from the other growth hormone peptides.",
          "GHK-Cu cream is used indefinitely, like any skincare.",
        ] },
        { t: "h", text: "Timing within a day" },
        { t: "list", items: [
          "Growth hormone peptides: before bed, on an empty stomach, because that's when the natural burst is biggest and food blunts it. A second dose on waking, before breakfast, is the common addition.",
          "Weight-loss peptides: once a week, same day, any time. The long half-life makes the hour irrelevant.",
          "Nasal brain peptides: morning for semax, any time for selank, and neither late in the day if sleep suffers.",
          "Recovery peptides: consistency matters more than the clock. Many split the day's dose in two because they wear off fast.",
          "PT-141 and melanotan: hours before you want the effect, on an empty stomach, because of the nausea.",
        ] },
        { t: "note", text: "Notice the pattern: the peptides with the most human data, the weight-loss drugs and tesamorelin, are used continuously by design. The ones cycled most aggressively are the ones we know least about. Cycling tracks uncertainty more than it tracks biology." },
      ],
    },
    {
      slug: "tracking",
      title: "Telling whether it worked",
      minutes: 6,
      free: false,
      summary: "What to measure, how often, and what a real change looks like against normal ups and downs.",
      body: [
        { t: "p", text: "The log in module two records what you did. This lesson is about deciding whether it did anything, which is a different skill, and one most people skip." },
        { t: "h", text: "Numbers that actually move" },
        { t: "list", items: [
          "Weight and waist, weekly, same conditions. Daily weight bounces around. A weekly average is signal.",
          "Sleep, as a one-line note each night or a wearable's score, because several peptides change sleep first.",
          "Resting heart rate and blood pressure, a few mornings a week, especially with anything in the weight-loss, tanning, desire or brain groups.",
          "Pain or function, on a simple zero-to-ten scale, for a recovery peptide. It's crude, and it beats memory.",
          "Training numbers, if you're an athlete: the same lift, the same run, the same interval, logged the same way. It's the most honest measure you have.",
          "Bloodwork, for the peptides where a marker exists: IGF-1 and fasting blood sugar for the growth hormone group, HbA1c and cholesterol for the weight-loss group. Module five covers timing.",
        ] },
        { t: "h", text: "What a real change looks like" },
        { t: "p", text: "It lasts. One good night and one bad night are noise. A better average over two weeks is a change. It fits the timeline: sleep changes within days, body composition within months, and anything that shows up the morning after the first dose is almost always expectation. And it survives stopping: if you drop a peptide and the number slides back over weeks, that's evidence. If nothing changes when you stop, that's evidence too." },
        { t: "h", text: "The two mistakes" },
        { t: "list", items: [
          "Giving the peptide credit for everything good that happened while taking it. The fix is one thing at a time, and the log.",
          "Ignoring \"nothing.\" A peptide that did nothing measurable in a fair test is a result worth writing down, because it's the one that saves you money next year.",
        ] },
        { t: "note", text: "A weekly review is the habit: ten minutes, the log open, one question. Did anything move that wouldn't have moved anyway?" },
      ],
    },
  ],
};

export const MODULE_5 = {
  n: 5,
  slug: "expectations-and-safety",
  title: "What to expect, and staying safe",
  summary: "Timelines, plateaus, side effects sorted by what they mean, medication interactions, bloodwork, and when to stop.",
  status: "ready",
  lessons: [
    {
      slug: "timelines",
      title: "What to expect, and when",
      minutes: 10,
      free: false,
      summary: "Peptide by peptide: what people notice first, how soon, and what never shows up.",
      body: [
        { t: "p", text: "Most disappointment in this market is a timing problem. A peptide judged after a week for an effect that takes three months gets dropped for no reason. A peptide kept for months for an effect that should have shown in days is money wasted. Here are the reported timelines, grouped by how fast anything is noticeable." },
        { t: "fig", id: "timeline", caption: "How soon anything shows up, by group. Judge a peptide inside its window, not before." },
        { t: "h", text: "Hours to days" },
        { t: "list", items: [
          "Nasal brain peptides: within the hour, gone within the day.",
          "PT-141 and melanotan: the sexual effects and nausea within hours. Visible tanning over one to two weeks with sun.",
          "Growth hormone peptides: sleep changes and vivid dreams in the first week. Everything else is months.",
          "Weight-loss peptides: appetite dropping within the first week at the starting dose, often before the scale moves.",
        ] },
        { t: "h", text: "Weeks" },
        { t: "list", items: [
          "Recovery peptides: reported improvement in tendon and soft-tissue pain at two to four weeks. Nothing by six weeks is generally taken as nothing.",
          "Weight-loss peptides: a pound or two a week once past the starting doses. The schedule means the full dose is months away.",
          "Thymosin alpha-1: no felt effect for most people. The measure is what happens over a season.",
          "KPV and gut-directed BPC-157: symptom change within two to three weeks, if at all.",
        ] },
        { t: "h", text: "Months" },
        { t: "list", items: [
          "Growth hormone group: body composition and recovery over eight to twelve weeks. IGF-1 moving on bloodwork within a few weeks.",
          "GHK-Cu cream: skin changes over two to three months, matching the trials.",
          "Tesamorelin: belly fat over three to six months, which is how long its trials ran.",
        ] },
        { t: "h", text: "Never, in any measurable way, for most people" },
        { t: "p", text: "The longevity peptides. Epithalon, pinealon, MOTS-c and injected NAD+ are taken for effects on processes measured in years, and the honest expectation is that nothing will be felt beyond maybe a sleep change or a placebo lift in energy. People who take them accept that. People who expect to feel them are set up to be disappointed, or to fool themselves." },
        { t: "h", text: "Plateaus" },
        { t: "p", text: "Every effect that shows up also levels off. Appetite partly returns on a weight-loss peptide at a steady dose. Sleep normalises on growth hormone peptides after the first weeks. Pain relief from a recovery peptide hits a floor. A plateau is not a signal to raise the dose. It's usually the effect size the peptide has, and raising the dose buys side effects rather than more effect." },
        { t: "note", text: "The question at each weekly review: is this peptide inside its expected window, past it, or was the expectation never realistic? The answer decides whether to wait, stop, or stop pretending." },
      ],
    },
    {
      slug: "side-effects",
      title: "Side effects, sorted by what they mean",
      minutes: 12,
      free: false,
      summary: "The ones almost everyone gets, the ones that mean lower the dose or stop, and the ones that mean a doctor today.",
      body: [
        { t: "p", text: "Side effects sort into three groups, and the sorting is the useful skill. The first group is the price of the peptide, and it fades. The second means the dose is wrong or the peptide is wrong for this person. The third isn't a peptide question any more." },
        { t: "fig", id: "triage", caption: "Three groups. The skill is knowing which one you are looking at." },
        { t: "h", text: "Group one: expected, and fading" },
        { t: "list", items: [
          "Redness or a small lump at the injection spot that lasts a day. Rotating spots and better technique fix most of it.",
          "Nausea in the days after stepping up a weight-loss peptide, or after each tanning or desire peptide dose.",
          "Flushing, mild headache and tiredness in the first days of most peptides.",
          "Vivid dreams and hunger on growth hormone peptides.",
          "The sulphur smell from glutathione, the sting of GHK-Cu, the head rush from TB-500.",
        ] },
        { t: "h", text: "Group two: stop, rethink, usually the dose" },
        { t: "list", items: [
          "Tingling, numbness or puffy hands on the growth hormone group. The classic sign of too much.",
          "Vomiting, or nausea that doesn't settle within a week of a weight-loss step-up. The step was too soon or too big.",
          "Ongoing irritability, insomnia or agitation on the brain peptides.",
          "Light-headedness or a blood pressure change on GHK-Cu, semax, PT-141 or melanotan.",
          "A new or changing mole on melanotan. Stop, and see the next group.",
          "Any injection spot that's hot, spreading, or lasting more than a couple of days.",
        ] },
        { t: "h", text: "Group three: a doctor, today" },
        { t: "list", items: [
          "Severe, lasting belly pain, with or without vomiting, on a weight-loss peptide. Pancreatitis and gallbladder problems show up this way.",
          "Chest pain, a racing or irregular heartbeat, or fainting, on anything.",
          "Signs of low blood sugar in anyone combining these with diabetes medication: shaking, sweating, confusion.",
          "An allergic reaction: hives, swelling of the face or throat, trouble breathing. Rare with peptides, not zero, especially with animal-derived products.",
          "A mole that has changed, on melanotan or not.",
          "Signs of infection at an injection spot: spreading redness, fever, pus.",
        ] },
        { t: "h", text: "The side effect nobody lists" },
        { t: "p", text: "A vial that isn't what it says. A side effect that doesn't match the peptide's known profile is, more often than people think, a contamination or identity problem with the product. Testing the vial, from module one, is the answer, and the lot number in your log is why it's possible." },
        { t: "warn", text: "The people in this market who get hurt are rarely hurt by a peptide doing what it's supposed to. They're hurt by ignoring group two until it becomes group three, or by a product that was never tested. Both are avoidable." },
      ],
    },
    {
      slug: "interactions",
      title: "Mixing with medications",
      minutes: 12,
      free: false,
      summary: "Blood sugar, blood pressure, thyroid, blood thinners, hormones, psychiatric medication. Where the overlap is real.",
      body: [
        { t: "p", text: "Almost no peptide in this course has a formal drug-interaction study, because almost none has been through the process that produces them. What we have is basic pharmacology: knowing what each peptide does lets you see where it overlaps with a medication. These are the overlaps that matter, grouped by the body system they share." },
        { t: "h", text: "Blood sugar" },
        { t: "list", items: [
          "Weight-loss peptides with insulin or certain diabetes pills: they add up, and blood sugar can go dangerously low. This is a prescriber's problem and only a prescriber can manage it.",
          "Growth hormone peptides with any diabetes medication: they push sugar up, which can undo control or hide it.",
          "Metformin sits in the middle and is usually the medication people are already on. With weight-loss peptides the combination is standard medical practice. With growth hormone peptides it needs sugar watched.",
        ] },
        { t: "h", text: "Blood pressure and heart" },
        { t: "list", items: [
          "PT-141 and melanotan raise pressure for a few hours. Combined with a stimulant, a decongestant or untreated high blood pressure, that matters. With blood pressure medication the result is unpredictable rather than dangerous, but it needs a cuff at home.",
          "Semax can raise pressure. Retatrutide raised heart rate in trials. Anyone on heart-rate medication for a heart condition is outside what anyone knows.",
          "NAD+ dripped in too fast causes chest tightness that's frightening in anyone with heart disease, which is why clinics go slowly.",
        ] },
        { t: "h", text: "How other pills get absorbed" },
        { t: "p", text: "The weight-loss peptides slow the stomach, which changes how pills are absorbed. Thyroid medication, the birth-control pill, and any drug with a narrow safe range are the ones people notice. PT-141 has a documented version of the same effect. Anyone on a medication where timing matters needs their prescriber to know a weight-loss peptide is in the picture." },
        { t: "h", text: "Thyroid" },
        { t: "p", text: "Growth hormone changes how thyroid hormones convert and can reveal an underactive thyroid. People on thyroid replacement sometimes need an adjustment while on growth hormone peptides, and the only way to know is a thyroid blood panel." },
        { t: "h", text: "Blood thinners and bleeding" },
        { t: "p", text: "No peptide here is a documented blood thinner. The recovery peptides act on blood vessels and, in animals, on platelets, and that's enough theoretical overlap that people on warfarin or a newer blood thinner tend to stay away or tell their prescriber. The same applies before any surgery: several peptides, the weight-loss ones most concretely, get stopped beforehand, and the anesthetist needs to know." },
        { t: "h", text: "Hormones" },
        { t: "list", items: [
          "Kisspeptin, and to a lesser degree the tanning and desire peptides, act on the sex-hormone system. Anyone on testosterone, estrogen, fertility treatment or a hormone-suppressing drug is in unstudied territory.",
          "Steroid medications (like prednisone) and growth hormone work against each other on several fronts, including blood sugar.",
          "Thymosin alpha-1 and any immune-suppressing drug work against each other by design.",
        ] },
        { t: "h", text: "Psychiatric medication" },
        { t: "p", text: "Selank and semax act on the same brain systems as anxiety medications, antidepressants and stimulants, in ways that were studied in Russia and not here. Cerebrolysin isn't given to people with epilepsy. Nobody on psychiatric medication should add any of these without their prescriber knowing. That's not caution for its own sake. The person best placed to notice a problem needs to know what could be causing it." },
        { t: "note", text: "The practical rule most experienced people use: any peptide that touches a system a medication is already managing gets mentioned to whoever prescribes that medication. Prescribers are more used to this conversation than people expect, and they'd rather know." },
      ],
    },
    {
      slug: "labs",
      title: "Bloodwork people run",
      minutes: 8,
      free: false,
      summary: "A baseline before you start, follow-ups by peptide group, and how to read your own results.",
      body: [
        { t: "p", text: "Bloodwork is how a decision about a peptide stops being a feeling. A baseline before starting and a follow-up a few months in is the pattern, and it costs less than most people think through direct-to-consumer lab services, where you order the test yourself and go to a local draw site." },
        { t: "h", text: "Baseline, before anything" },
        { t: "list", items: [
          "A standard metabolic panel and cholesterol. The floor for anything to do with weight or metabolism, and the thing most likely to reveal a reason not to start.",
          "Fasting blood sugar and HbA1c (your three-month sugar average). Essential before the growth hormone or weight-loss groups.",
          "A complete blood count and liver enzymes. General health, and a reference point for later.",
          "A thyroid panel, if the growth hormone group is planned or there's any thyroid history.",
          "IGF-1, if the growth hormone group is planned. It's the marker those peptides move.",
          "Testosterone and related hormones, if anything touching the sex-hormone system is planned, or for anyone who'd want to know anyway.",
        ] },
        { t: "h", text: "Follow-up, by peptide group" },
        { t: "list", items: [
          "Growth hormone group: IGF-1 and fasting blood sugar or HbA1c at six to twelve weeks. IGF-1 rising toward the top of the normal range is the effect. Blood sugar rising is the cost. Both above range is the signal to stop.",
          "Weight-loss group: HbA1c and cholesterol at three months, plus a kidney check if there's been a lot of vomiting or dehydration.",
          "Anything long-term: repeat the baseline at six months, then yearly.",
          "Recovery, brain and immune peptides: nothing specific to track in blood. The log is the instrument.",
        ] },
        { t: "h", text: "Reading the result" },
        { t: "p", text: "Normal ranges are wide, and a value moving within the range is often the story. IGF-1 going from the bottom of the range to the middle is a peptide working. Blood sugar going from the middle to the top is a peptide costing something, even though both numbers are technically \"normal.\" Compare to your own baseline, not to the range." },
        { t: "note", text: "A clinician reading results beats a spreadsheet reading them, and this is one of the places a single visit pays for itself. Bring the log." },
      ],
    },
    {
      slug: "when-to-stop",
      title: "When to stop",
      minutes: 6,
      free: false,
      summary: "The signals, how to stop, and the difference between a side effect and a reason.",
      body: [
        { t: "p", text: "Stopping is the decision people are worst at, in both directions: stopping a peptide in week one because of an expected side effect, and continuing one for months because stopping would mean admitting it did nothing." },
        { t: "h", text: "Stop now" },
        { t: "list", items: [
          "Anything in group three of the side-effects lesson. That's a doctor's call and the peptide is already stopped by the time they're involved.",
          "A group-two side effect that came back after lowering the dose. The peptide is wrong for this person, not the dose.",
          "Bloodwork that moved the wrong way past your baseline in a way the peptide explains.",
          "A vial that failed a test, or a batch other buyers have reported. Not worth the argument.",
        ] },
        { t: "h", text: "Stop at the end of the window" },
        { t: "list", items: [
          "A peptide past its expected timeline with nothing in the log to show for it. That result is a result. Write it down and stop.",
          "A goal reached. The injury healed, the tan is there, the season is over. Continuing is habit.",
          "The end of a planned cycle, for the peptides where cycling has a mechanism.",
        ] },
        { t: "h", text: "How to stop" },
        { t: "p", text: "Almost every peptide in this course can simply be stopped. The exceptions are worth knowing. The weight-loss peptides bring appetite back, which is better planned for than surprised by, and some people taper the dose down over a month or two. The growth hormone group is stopped outright; the natural bursts just return to baseline. Nothing here causes withdrawal the way a benzodiazepine or a steroid does." },
        { t: "h", text: "The difference between a side effect and a reason" },
        { t: "p", text: "A side effect is a cost, and costs get weighed. Three days of nausea at each weight-loss step is a cost most people pay for the result. A reason is a cost that isn't worth any result, or a sign the peptide is doing something other than what it should. Puffy hands are a cost that says lower the dose. A changing mole is a reason. The log, the timeline and the bloodwork are how you tell them apart." },
        { t: "note", text: "The habit that protects people: decide before you start what would make you stop, and write it at the top of the log. It's much easier to follow a rule you made calm than to make one mid-course." },
      ],
    },
  ],
};

export const MODULE_6 = {
  n: 6,
  slug: "staying-current",
  title: "Keeping up",
  summary: "How to read a study without a science degree, how to spot hype, how the rules are changing, and how the members' digest works.",
  status: "ready",
  lessons: [
    {
      slug: "reading-a-study",
      title: "Reading a study without a science degree",
      minutes: 12,
      free: false,
      summary: "Six questions that tell you whether a study means what someone says it means.",
      body: [
        { t: "p", text: "Most claims in this market trace back to a real study. The claim is usually still wrong, because the study was in rats, or in twelve people, or measured something other than what the claim says. Reading the study takes ten minutes and doesn't require understanding statistics. It requires six questions." },
        { t: "h", text: "The six questions" },
        { t: "list", items: [
          "Who was it in? Cells in a dish, animals, or people. Most peptide studies are the first two, and results don't transfer to people reliably. Drugs that look great in rodents fail in humans far more often than they succeed.",
          "How many? A study of twelve people can show a hint. It can't show safety, and it can't show the result wasn't luck. Find the number in the methods, and be suspicious of anything under fifty presented as settled.",
          "Compared with what? A study with no placebo group measures the placebo effect plus the peptide. For anything you feel rather than measure, pain, mood, energy, the placebo effect is large.",
          "What was measured? A study that measured a blood marker isn't a study of the result you want. IGF-1 going up is not muscle. An enzyme in a dish is not a longer life.",
          "At what dose, and how? Animal doses per kilogram are often many times what people use, given in ways people don't use. A rat injected into its belly cavity with a huge dose says little about a tiny dose under a person's skin.",
          "Who paid? Studies funded by the maker aren't automatically wrong, but they're the ones where the outcome measure was chosen carefully. A marginal result from the compound's developer is a marginal result.",
        ] },
        { t: "h", text: "Where the summary lies by leaving things out" },
        { t: "p", text: "The abstract, the short summary at the top of a paper, reports the positive finding. It leaves out that it was one of eight things measured, that it showed up in a subgroup, that it was only at the highest dose, or that it was statistically significant and practically tiny. The habit that catches this is reading the results table, not the abstract, and asking whether the number in the table would change what you'd do if it were true." },
        { t: "h", text: "Where to read" },
        { t: "p", text: "PubMed, a free government database, indexes almost everything, and most abstracts are free. Many full papers are free through the journal or the authors' university. A vendor page that cites a study should link to it. If the link goes to the vendor's own summary, that's the tell. The reference pages on this site list the key study for each peptide, and the members' digest goes through new ones as they appear." },
        { t: "note", text: "A useful test for any claim: could the person making it tell you how many people were in the study and what was measured? If yes, listen. If not, they read the abstract, or the vendor's summary of it." },
      ],
    },
    {
      slug: "hype-filters",
      title: "Spotting hype",
      minutes: 8,
      free: false,
      summary: "The tells in an influencer post, a vendor page, and a forum thread.",
      body: [
        { t: "p", text: "Three sources produce most of what people believe about peptides, and each has its own way of being wrong. Knowing the pattern is faster than checking every claim." },
        { t: "h", text: "The influencer post" },
        { t: "list", items: [
          "A transformation with a peptide named and nothing else mentioned: no diet, no training, no other drugs. The peptide is the sponsor, not the cause.",
          "A discount code. The recommendation is paid for, by a vendor whose product the influencer hasn't tested.",
          "Certainty. Nobody who has read the research on most of these peptides is certain about them. Certainty is a sales voice.",
          "Stacks of six peptides presented as a daily routine. Someone taking six things can't know what any of them does, and neither can their audience.",
        ] },
        { t: "h", text: "The vendor page" },
        { t: "list", items: [
          "Medical claims: heals, treats, cures, reverses. Either they don't know the law or they're ignoring it. Either way, not a source.",
          "A study cited with no link, or a link to the vendor's own summary.",
          "Lab reports that all look the same. Module one.",
          "Permanent discounts and countdown timers. Pricing theatre, and a sign the \"full price\" is fiction.",
          "The phrase \"research use only\" right next to a paragraph about what it does in your body. The disclaimer and the sales copy are talking to different regulators.",
        ] },
        { t: "h", text: "The forum thread" },
        { t: "list", items: [
          "Dose ranges with no source. They usually trace to one post years ago that everyone has repeated. The number may be fine. The confidence is inherited.",
          "The one person it worked miracles for. A single story proves it happened to one person, and nothing about how common that is.",
          "Advice that hasn't been updated for what's been learned since, especially about the weight-loss peptides, where the picture changed fast.",
          "The genuinely useful part: community test results, side-effect reports at scale, and vendors named for failing. Forums are best as a record of what went wrong, and worst as a guide to what to do.",
        ] },
        { t: "h", text: "The filter in one line" },
        { t: "p", text: "Who benefits if I believe this, and what would they have to show me for it to be true? A source that benefits and can't show anything is marketing, however it's dressed." },
      ],
    },
    {
      slug: "regulation",
      title: "How the rules are changing",
      minutes: 10,
      free: false,
      summary: "The 2023 pharmacy decision, the end of the weight-loss drug shortage, what enforcement looks like, and where it's going.",
      body: [
        { t: "p", text: "The research-chemical market lives in the gap between what's legal to sell as a chemical and what's legal to sell as a medicine. That gap has been narrowing, and the direction matters for anyone relying on it." },
        { t: "h", text: "2023: the pharmacy decision" },
        { t: "p", text: "Compounding pharmacies, which mix medications to order, had been a legal way to get several of these peptides with a prescription. In 2023 the FDA reviewed a list of substances nominated for compounding and put BPC-157 and several other popular peptides in a category it considers to carry significant safety risks, meaning pharmacies may not make them. The reason given was a lack of data on human safety, not evidence of harm. The effect was to push demand from a prescription route to the research market, where the data problem is worse." },
        { t: "h", text: "2024 to 2025: the weight-loss shortage ends" },
        { t: "p", text: "While brand-name semaglutide and tirzepatide were in shortage, compounding pharmacies were allowed to make copies, and a big telehealth industry grew on that. The FDA declared the tirzepatide shortage over in late 2024 and semaglutide in early 2025, and the copies were phased out over the following months. Some telehealth sellers moved to tweaked formulas to stay in a grey zone. Many customers moved to research-chemical vendors. That's why those two peptides now dominate the market, and why counterfeits of them are its biggest quality problem." },
        { t: "h", text: "What enforcement looks like" },
        { t: "list", items: [
          "Warning letters to sellers who make medical claims. This is the main tool, and it's aimed at vendors, not buyers.",
          "Payment processors cutting vendors off. Not enforcement in the legal sense, but the thing that actually shuts vendors down, and the reason the \"payment shuffle\" from module one exists.",
          "Customs seizing imported product, which hits vendors' supply and occasionally an individual order.",
          "Sport. WADA bans most of these peptides, and drug testing is the one place an individual user faces a direct consequence.",
        ] },
        { t: "h", text: "Where it's going" },
        { t: "p", text: "Two things are happening at once. Some peptides are becoming medicines: retatrutide is in final trials, SS-31 got approved for a rare disease, and the weight-loss class is becoming as routine as cholesterol pills. As that happens, the prescription route for those gets easier and the research market for them gets squeezed. Meanwhile, the peptides with no path to approval, which is most of the recovery and longevity group, drift further from any legitimate route, and pressure on the vendors selling them grows. The likely shape of the next few years is a split market: prescriptions for what has data, and a smaller, more watched grey market for what doesn't." },
        { t: "note", text: "The practical takeaway for a buyer is the one module one made: the only quality control in this market is the one you do yourself, and the amount required is going up, not down." },
      ],
    },
    {
      slug: "the-digest",
      title: "The members' digest",
      minutes: 4,
      free: false,
      summary: "How updates reach you, and how to ask a question about the material.",
      body: [
        { t: "p", text: "The evidence for most of these peptides is thin, which means it changes. One good human trial moves a peptide from one grade to another. A regulatory decision changes what's available. A round of community test results changes which vendors are worth trusting. A static course would be out of date within a year, so this one isn't." },
        { t: "h", text: "What the digest is" },
        { t: "list", items: [
          "An email when something changes: a new study worth reading, graded and summarised the way the peptide lessons are; a regulatory decision; a lesson rewritten because the evidence moved.",
          "The change log for the course, so members can see exactly what was updated and why.",
          "Community test results and vendor news, summarised without naming vendors as recommendations.",
          "Answers to members' questions about the material, written up where the answer helps everyone.",
        ] },
        { t: "h", text: "How to ask" },
        { t: "p", text: "Reply to any digest email. Questions about the material get answered: what a lesson meant, how to read a study, what a word means, whether a piece of news changes anything. That's the line, and it's worth repeating: questions about a peptide get an answer, and questions about you get pointed to a clinician, because that's the only honest answer to them." },
        { t: "h", text: "What founders get" },
        { t: "p", text: "Everything above, free for the first year, and the founder price on the membership after that if they want to keep it. Every update to every lesson, for as long as the course exists, regardless." },
        { t: "note", text: "The most useful thing a member can send is a question that shows a lesson was unclear. Those turn into rewrites, and the rewrite is what the next reader gets." },
      ],
    },
  ],
};
