/**
 * Modules 4, 5 and 6: stacking, expectations and safety, staying current.
 * Same block format and the same line as the rest of the course: reported
 * practice and published evidence, explained to an audience, never a plan for
 * a person.
 */

export const MODULE_4 = {
  n: 4,
  slug: "stacking",
  title: "Building a stack",
  summary: "One variable at a time, what pairs, what conflicts, and how cycling actually works.",
  status: "ready",
  lessons: [
    {
      slug: "one-variable",
      title: "One variable at a time",
      minutes: 8,
      free: false,
      summary: "Why starting three compounds at once tells you nothing, and the order people use instead.",
      body: [
        { t: "p", text: "The most common way people waste money in this market is not buying a bad vial. It is starting three compounds in the same week, feeling different a month later, and having no idea which one did it, or whether any of them did. A stack built that way cannot be improved, because nothing in it can be tested." },
        { t: "h", text: "The rule" },
        { t: "p", text: "One new thing at a time, held long enough to judge, with everything else steady. For most compounds in this course that means two to four weeks before the next change. For the growth hormone group and the GLP-1s, whose effects build over months, it means longer. The log from module two is what makes the judgment possible." },
        { t: "h", text: "The order experienced users tend to follow" },
        { t: "list", items: [
          "The compound with the clearest evidence for the actual problem, alone. If the problem is a tendon, that is a recovery peptide, not a growth hormone stack that might also help.",
          "Held at a low reported dose first, then raised if nothing happens, rather than started high and lowered after side effects.",
          "A second compound only once the first has been judged: kept because it helped, or dropped because it did not. Never added to rescue a first compound that is not working.",
          "Blends last, and only from components already run separately. A blend is a conclusion, not a starting point.",
        ] },
        { t: "h", text: "Everything else held steady" },
        { t: "p", text: "A new training block, a diet change, a new supplement, a change in sleep: any of these produces effects as large as most peptides do. If one of them changes in the same window, the log cannot separate it. The discipline is boring and it is the only way a person ends up knowing what works for them rather than believing it." },
        { t: "note", text: "The question that sorts this out quickly: if this compound did nothing, would I be able to tell? If the answer is no, the stack is not ready for it." },
      ],
    },
    {
      slug: "what-pairs",
      title: "What pairs, and why",
      minutes: 14,
      free: false,
      summary: "The stacks on the reference site, explained: the mechanism behind each pairing.",
      body: [
        { t: "p", text: "A pairing is worth making when the two compounds act through different mechanisms on the same goal, or when one covers a weakness of the other. Most of the blends sold in this market meet the first test. Few have any evidence for the combination itself, so what follows is the reasoning behind each, not a finding." },
        { t: "h", text: "GHRH analogue plus ipamorelin" },
        { t: "p", text: "The one pairing with a pharmacological basis. A GHRH analogue enlarges a growth hormone pulse and a ghrelin mimetic triggers one while suppressing the hormone that would blunt it. Together they produce a larger pulse than either alone, in human studies of the individual mechanisms. CJC-1295 without DAC plus ipamorelin is the standard version; tesamorelin plus ipamorelin is the expensive one. Taken together, before bed, on an empty stomach." },
        { t: "h", text: "BPC-157 plus TB-500" },
        { t: "p", text: "The recovery pairing, sold as Wolverine. The logic is complementary action: one on vessel growth and local signalling, the other on cell migration and inflammation. Both have animal evidence alone and neither has human evidence together. Because their reported schedules differ, a blend compromises one of them, and people who run them separately usually dose BPC-157 daily and TB-500 twice a week." },
        { t: "h", text: "GLP-1 plus a growth hormone secretagogue" },
        { t: "p", text: "The most-discussed pairing among people on semaglutide or tirzepatide, aimed at the muscle loss those drugs cause. The reasoning is that growth hormone favours lean mass retention during a deficit. There is no trial of the combination, and the blood sugar effects run in opposite directions, which is either a balance or a mess depending on the person. The evidence-based version of this pairing is resistance training and protein, which have trials." },
        { t: "h", text: "GHK-Cu plus a recovery peptide" },
        { t: "p", text: "The Glow blend. Collagen production alongside tissue repair, for skin and healing together. Coherent as mechanism, unstudied as a combination, and complicated by GHK-Cu's injection pain, which makes people abandon the whole blend for a side effect that belongs to one component." },
        { t: "h", text: "Selank plus semax" },
        { t: "p", text: "A common pairing among nasal users: one for calm, one for drive. They come from the same research programme and were sometimes studied together there. People report the combination as focus without edge. Because both are short-acting and taken as needed, they are also easy to run separately first, which is what the one-variable rule asks." },
        { t: "h", text: "Thymosin alpha-1 alongside almost anything" },
        { t: "p", text: "Not a pairing so much as a background. Because its safety record is long and its effects are on the immune system rather than any of the other axes, it is the compound most often run alongside others without confusing the picture." },
        { t: "note", text: "Every pairing above is stronger as two vials than as one blend, because two vials can be dosed on their own schedules and dropped one at a time. Blends are for people who already know the pairing works for them and want the convenience." },
      ],
    },
    {
      slug: "what-conflicts",
      title: "What conflicts",
      minutes: 10,
      free: false,
      summary: "Compounds that compete, overlap or compound each other's side effects.",
      body: [
        { t: "p", text: "Conflicts in this market are rarely dangerous chemistry. They are two compounds pushing the same physiology, two compounds sharing a side effect, or two compounds that make the other's effect unreadable." },
        { t: "h", text: "Pushing the same axis twice" },
        { t: "list", items: [
          "Two GHRH analogues together, or a GHRH analogue plus synthetic growth hormone. The pituitary can only release what it has, and adding synthetic growth hormone on top defeats the feedback loop that made the secretagogue approach attractive in the first place.",
          "Two GLP-1 compounds. Nobody plans this, but people switching from semaglutide to tirzepatide sometimes overlap them, and the half-lives mean both are active for a week or more. Switches are done by stopping one and waiting.",
          "Melanotan 2 plus PT-141. Same receptor family, and PT-141 was derived from melanotan 2. Stacking them doubles the nausea and the blood pressure effect for no additional benefit.",
        ] },
        { t: "h", text: "Shared side effects that add up" },
        { t: "list", items: [
          "Blood sugar: growth hormone secretagogues raise it, GLP-1s lower it, and stimulant-type nootropics can push it either way. The combination is a moving target that only bloodwork can read.",
          "Blood pressure: semax, PT-141, melanotan 2 and high-dose NAD+ can each raise it or move it. Together, in someone who is already borderline, they are a problem.",
          "Nausea: the GLP-1s, PT-141, melanotan 2 and rapid NAD+ all cause it. Two at once is often the reason someone concludes a compound is intolerable when it was the pairing.",
          "Water retention and joint aches: the growth hormone group, and less predictably the recovery peptides. Together they are the usual explanation for swollen hands.",
        ] },
        { t: "h", text: "Combinations that make each other unreadable" },
        { t: "p", text: "Two compounds started together for the same goal, whatever they are. The conflict is not in the body; it is in the log. And any compound started in the same fortnight as a new medication, because the medication's side effects will be attributed to the peptide or the reverse." },
        { t: "h", text: "With medications" },
        { t: "p", text: "The overlaps that matter are covered in module five. The short list: anything that lowers blood sugar with the GLP-1s or the growth hormone group; anything for blood pressure with the melanocortin compounds and semax; sedatives with selank; anticoagulants with anything that affects vessels or platelets, which includes several of the recovery peptides on theory if not on evidence." },
        { t: "warn", text: "None of these conflicts is documented in a trial, because no trial has run the combinations. That cuts both ways. The absence of a documented conflict is not the presence of safety." },
      ],
    },
    {
      slug: "cycling",
      title: "Cycling and timing",
      minutes: 10,
      free: false,
      summary: "On and off periods as practised, receptor sensitivity, and the compounds where cycling is not optional.",
      body: [
        { t: "p", text: "Cycling means taking a compound for a period and then stopping for a period. In this market it is practised for three different reasons that get confused with each other, and knowing which applies to a compound tells you whether a break is physiology or superstition." },
        { t: "h", text: "Reason one: receptors adapt" },
        { t: "p", text: "Repeated signalling through a receptor tends to reduce that receptor's sensitivity. The growth hormone secretagogues are the clearest case: continuous use produces a smaller pulse over time, and breaks restore it. Selank and semax users report tolerance with daily use. The break here has a mechanism, and a typical pattern is eight to twelve weeks on and four off for the growth hormone group, and days rather than weeks for the nasal nootropics." },
        { t: "h", text: "Reason two: the job is done" },
        { t: "p", text: "Recovery peptides are run for the length of an injury. Thymosin alpha-1 is run through an illness or a season. Melanotan is run until the tan is where someone wants it. There is no reason to continue past the goal, and the break is simply stopping." },
        { t: "h", text: "Reason three: nobody knows" },
        { t: "p", text: "The longevity compounds and the Russian bioregulators are cycled in short courses with long gaps because that is how their originating protocols ran, and because taking an unstudied compound for limited periods is the conservative default. The break is caution, not evidence. It is still the right default." },
        { t: "h", text: "The compounds where cycling is not the point" },
        { t: "list", items: [
          "The GLP-1s are long-term drugs. Stopping returns appetite and, in trials, most of the weight within a year. A break is a decision to stop, and it is made with that understood.",
          "Tesamorelin at its approved use is continuous. Cycling it is a research-market habit borrowed from the other secretagogues.",
          "Topical GHK-Cu is used indefinitely, like any skincare.",
        ] },
        { t: "h", text: "Timing within a day" },
        { t: "list", items: [
          "Growth hormone secretagogues: before bed, on an empty stomach, because that is when the natural pulse is largest and food blunts it. A second dose on waking, fasted, is the common addition.",
          "GLP-1s: once weekly, same day, any time. The half-life makes the hour irrelevant.",
          "Nasal nootropics: morning for semax, any time for selank, and not late in the day for either if sleep suffers.",
          "Recovery peptides: consistency matters more than clock time. Many split the day's dose in two because of the short half-life.",
          "PT-141 and melanotan: hours before the intended effect, on an empty stomach, because of the nausea.",
        ] },
        { t: "note", text: "The pattern to notice: the compounds with the most human data, the GLP-1s and tesamorelin, are used continuously by design. The compounds cycled most aggressively are the ones about which least is known. Cycling tracks uncertainty more than it tracks physiology." },
      ],
    },
    {
      slug: "tracking",
      title: "Tracking what happened",
      minutes: 6,
      free: false,
      summary: "Markers people track, how often, and what a real change looks like against noise.",
      body: [
        { t: "p", text: "The log in module two records what was done. This lesson is about deciding whether it did anything, which is a different skill and one most people skip." },
        { t: "h", text: "Markers that actually move" },
        { t: "list", items: [
          "Weight and waist, weekly, same conditions. Daily weight is noise; a weekly average is signal.",
          "Sleep, as a nightly one-line note or a wearable's score, because several compounds change it first.",
          "Resting heart rate and blood pressure, a few mornings a week, especially with anything in the metabolic, melanocortin or nootropic groups.",
          "Pain or function, on a simple zero-to-ten scale, for a recovery compound. The scale is crude and it is far better than memory.",
          "Bloodwork, for the compounds where a marker exists: IGF-1 and fasting glucose for the growth hormone group, HbA1c and lipids for the metabolic group. Module five covers timing.",
        ] },
        { t: "h", text: "What a real change looks like" },
        { t: "p", text: "It persists. A good night and a bad night are noise; a better average over two weeks is a change. It has a plausible timeline: sleep changes within days, body composition within months, and anything that appears the morning after the first dose is almost always expectation. And it survives stopping: if a compound is dropped and the marker slides back over weeks, that is evidence. If nothing changes when it stops, that is evidence too." },
        { t: "h", text: "The two errors" },
        { t: "list", items: [
          "Crediting the compound with everything good that happened while taking it. The fix is the one-variable rule and the log.",
          "Ignoring nothing. A compound that did nothing measurable in a fair trial is a result worth writing down, because it is the one that saves money next year.",
        ] },
        { t: "note", text: "A weekly review is the habit: ten minutes, the log open, one question. Did anything move that would not have moved anyway?" },
      ],
    },
  ],
};

export const MODULE_5 = {
  n: 5,
  slug: "expectations-and-safety",
  title: "Expectations and safety",
  summary: "Timelines, plateaus, side effects, interactions, and when to stop.",
  status: "ready",
  lessons: [
    {
      slug: "timelines",
      title: "What to expect and when",
      minutes: 10,
      free: false,
      summary: "Compound by compound: what people notice first, when, and what never shows up.",
      body: [
        { t: "p", text: "Most disappointment in this market is a timeline problem. A compound judged after a week for an effect that takes three months is a compound wrongly dropped, and a compound kept for months for an effect that should have shown in days is money wasted. These are the reported timelines, grouped by how fast anything is noticeable." },
        { t: "h", text: "Hours to days" },
        { t: "list", items: [
          "Nasal nootropics: within the hour, gone within the day.",
          "PT-141 and melanotan: the sexual and nausea effects within hours; visible tanning over one to two weeks with UV.",
          "Growth hormone secretagogues: sleep changes and vivid dreams in the first week. Everything else is months.",
          "GLP-1s: appetite loss within the first week at the starting dose, often before any weight moves.",
        ] },
        { t: "h", text: "Weeks" },
        { t: "list", items: [
          "Recovery peptides: reported improvement in tendon and soft-tissue pain at two to four weeks. Nothing by six weeks is generally taken as nothing.",
          "GLP-1s: weight moving at a pound or two a week once past the starting doses; the schedule means the full dose is months away.",
          "Thymosin alpha-1: no felt effect for most people; the marker is what happens over a season.",
          "KPV and gut-directed BPC-157: symptom change within two to three weeks if at all.",
        ] },
        { t: "h", text: "Months" },
        { t: "list", items: [
          "Growth hormone group: body composition and recovery over eight to twelve weeks, IGF-1 movement on bloodwork within a few weeks.",
          "GHK-Cu, topical: skin changes over two to three months, consistent with the trials.",
          "Tesamorelin: visceral fat over three to six months, which is the length of its trials.",
        ] },
        { t: "h", text: "Never, in any measurable way, for most people" },
        { t: "p", text: "The longevity compounds. Epithalon, pinealon, MOTS-c, and injected NAD+ are taken for effects on processes measured in years, and the honest expectation is that nothing will be felt beyond a possible sleep change or a placebo lift in energy. People who take them accept that. People who expect to feel them are set up to be disappointed or to fool themselves." },
        { t: "h", text: "Plateaus" },
        { t: "p", text: "Every effect that appears also levels off. Appetite returns partially on GLP-1s at a stable dose. Sleep normalises on secretagogues after the first weeks. Pain relief from recovery peptides reaches a floor. A plateau is not a signal to raise the dose; it is usually the effect size the compound has, and raising the dose buys side effects rather than more effect." },
        { t: "note", text: "The question at each review: is this compound within its expected window, past it, or was the expectation never realistic? The answer decides whether to wait, stop, or stop pretending." },
      ],
    },
    {
      slug: "side-effects",
      title: "Side effects, common and rare",
      minutes: 12,
      free: false,
      summary: "The ones almost everyone gets, the ones that mean stop, and the ones that mean a clinician today.",
      body: [
        { t: "p", text: "Side effects sort into three groups, and the sorting is the useful skill. The first group is the price of the compound and fades. The second means the dose is wrong or the compound is wrong for this person. The third is not a peptide question any more." },
        { t: "h", text: "Group one: expected, fading" },
        { t: "list", items: [
          "Injection-site redness or a small lump lasting a day. Rotation and technique fix most of it.",
          "Nausea in the days after a GLP-1 step-up, or after each melanocortin dose.",
          "Flushing, mild headache and fatigue in the first days of most compounds.",
          "Vivid dreams and hunger on secretagogues.",
          "The sulphur smell of glutathione, the sting of GHK-Cu, the head rush of TB-500.",
        ] },
        { t: "h", text: "Group two: stop, reassess, usually the dose" },
        { t: "list", items: [
          "Tingling, numbness or swollen hands on the growth hormone group. Classic sign of too much.",
          "Vomiting, or nausea that does not settle within a week of a GLP-1 step. The step was too soon or too large.",
          "Persistent irritability, insomnia or agitation on the nootropics.",
          "Light-headedness or a blood pressure change on GHK-Cu, semax, PT-141 or melanotan.",
          "A new or changing mole on melanotan. Stop, and see the next group.",
          "Any injection-site reaction that is hot, spreading, or lasting more than a couple of days.",
        ] },
        { t: "h", text: "Group three: a clinician, today" },
        { t: "list", items: [
          "Severe persistent abdominal pain, with or without vomiting, on a GLP-1. Pancreatitis and gallbladder disease present this way.",
          "Chest pain, a racing or irregular heartbeat, or fainting, on anything.",
          "Signs of low blood sugar in anyone combining these compounds with diabetes medication: shaking, sweating, confusion.",
          "An allergic reaction: hives, swelling of the face or throat, difficulty breathing. Rare with peptides and not zero, especially with animal-derived products.",
          "A mole that has changed, on melanotan or not.",
          "Signs of infection at an injection site: spreading redness, fever, pus.",
        ] },
        { t: "h", text: "The side effect nobody lists" },
        { t: "p", text: "A vial that is not what it says. A side effect that does not match the compound's known profile is, more often than people think, a contamination or identity problem with the product. Module one's testing lesson is the response, and the lot number in the log is why it is possible." },
        { t: "warn", text: "The people in this market who get hurt are rarely hurt by a compound working as described. They are hurt by ignoring group two until it becomes group three, or by a product that was never tested. Both are avoidable." },
      ],
    },
    {
      slug: "interactions",
      title: "Interactions with medications",
      minutes: 12,
      free: false,
      summary: "Blood sugar, blood pressure, thyroid, anticoagulants, hormones. Where the overlap is real.",
      body: [
        { t: "p", text: "Almost no compound in this course has a formal interaction study, because almost none has been through the process that produces them. What exists is pharmacology: knowing what each compound does lets you see where it overlaps with a medication. These are the overlaps that matter, grouped by the system they share." },
        { t: "h", text: "Blood sugar" },
        { t: "list", items: [
          "GLP-1s with insulin or sulfonylureas: additive glucose lowering, real hypoglycaemia risk. This is a prescriber's problem and only a prescriber can manage it.",
          "Growth hormone secretagogues with any diabetes medication: they push glucose up, which can undo control or mask it.",
          "Metformin sits in the middle and is usually the medication people are already on. The combination with GLP-1s is standard in clinical practice; with secretagogues it needs glucose watched.",
        ] },
        { t: "h", text: "Blood pressure and heart" },
        { t: "list", items: [
          "PT-141 and melanotan raise pressure transiently; combined with a stimulant, decongestant or an untreated hypertension they matter. With blood pressure medication the interaction is unpredictable rather than dangerous, but it needs a cuff at home.",
          "Semax can raise pressure. Retatrutide raised heart rate in trials. Anyone on rate-controlling medication for a heart condition is outside what anyone knows.",
          "NAD+ infused quickly causes chest tightness that is alarming in anyone with heart disease, and is why clinics run it slowly.",
        ] },
        { t: "h", text: "Absorption of other drugs" },
        { t: "p", text: "The GLP-1s slow stomach emptying, which changes how oral medications are absorbed. Thyroid medication, the contraceptive pill, and any drug with a narrow dose window are the ones that show up. PT-141 has a documented version of the same effect with naltrexone. Anyone on a medication where timing matters needs their prescriber to know a GLP-1 is in the picture." },
        { t: "h", text: "Thyroid" },
        { t: "p", text: "Growth hormone changes the conversion of thyroid hormones and can unmask low thyroid function. People on thyroid replacement sometimes need adjustment while on secretagogues, and the only way to know is a thyroid panel." },
        { t: "h", text: "Anticoagulants and bleeding" },
        { t: "p", text: "No peptide here is a documented anticoagulant. The recovery peptides act on blood vessels and, in animals, on platelets, and that is enough theoretical overlap that people on warfarin or a direct anticoagulant tend to stay away from them or tell their prescriber. The same applies before any surgery: several compounds here, the GLP-1s most concretely, are stopped beforehand, and the anaesthetist needs to know." },
        { t: "h", text: "Hormones" },
        { t: "list", items: [
          "Kisspeptin, and to a lesser degree the melanocortins, interact with the reproductive axis. Anyone on testosterone, oestrogen, fertility treatment or a GnRH-based drug is in unstudied territory.",
          "Corticosteroids and growth hormone oppose each other on several fronts, including glucose.",
          "Thymosin alpha-1 and any immunosuppressant work against each other by design.",
        ] },
        { t: "h", text: "Psychiatric medication" },
        { t: "p", text: "Selank and semax act on the same systems as anxiolytics, antidepressants and stimulants, in ways that were studied in Russia and not here. Cerebrolysin is contraindicated in epilepsy. Nobody on psychiatric medication should add any of these without a prescriber knowing, and that is not caution for its own sake; it is that the person best placed to notice a problem needs to know what could be causing it." },
        { t: "note", text: "The practical rule most experienced people use: any compound that touches a system a medication is already managing gets disclosed to whoever prescribes that medication. Prescribers are more used to this conversation than people expect, and they would rather know." },
      ],
    },
    {
      slug: "labs",
      title: "Bloodwork people run",
      minutes: 8,
      free: false,
      summary: "Baseline and follow-up markers commonly tracked, and what they are for.",
      body: [
        { t: "p", text: "Bloodwork is how a decision about a compound stops being a feeling. A baseline before starting and a follow-up a few months in is the pattern, and it is cheaper than most people assume through direct-to-consumer lab services." },
        { t: "h", text: "Baseline, before anything" },
        { t: "list", items: [
          "A standard metabolic panel and lipids. The floor for anything metabolic, and the thing most likely to reveal a reason not to start.",
          "Fasting glucose and HbA1c. Essential before the growth hormone or metabolic groups.",
          "A complete blood count and liver enzymes. General health, and a reference for later.",
          "Thyroid panel, if the growth hormone group is planned or there is any thyroid history.",
          "IGF-1, if the growth hormone group is planned. It is the marker those compounds move.",
          "Testosterone and related hormones, if anything touching the reproductive axis is planned, or for anyone who would want to know anyway.",
        ] },
        { t: "h", text: "Follow-up, by compound group" },
        { t: "list", items: [
          "Growth hormone group: IGF-1 and fasting glucose or HbA1c at six to twelve weeks. IGF-1 rising into the upper reference range is the effect; glucose rising is the cost. Both above range is the signal to stop.",
          "GLP-1s: HbA1c and lipids at three months, and a check on kidney function if there has been significant vomiting or dehydration.",
          "Anything long-term: repeat the baseline panel at six months, then yearly.",
          "Recovery, nootropic and immune compounds: nothing specific to track on bloodwork. The log is the instrument.",
        ] },
        { t: "h", text: "Reading the result" },
        { t: "p", text: "Reference ranges are wide, and a value moving within the range is often the story. IGF-1 that goes from the bottom of the range to the middle is a compound working. Glucose that goes from the middle to the top is a compound costing something, even though both numbers are technically normal. Compare to your own baseline, not to the range." },
        { t: "note", text: "A clinician reading results is better than a spreadsheet reading them, and this is one of the places where a single visit pays for itself. Bring the log." },
      ],
    },
    {
      slug: "when-to-stop",
      title: "When to stop",
      minutes: 6,
      free: false,
      summary: "The signals, and the difference between a side effect and a reason.",
      body: [
        { t: "p", text: "Stopping is the decision people are worst at, in both directions: stopping a compound in week one because of an expected side effect, and continuing one for months because stopping would mean admitting it did nothing." },
        { t: "h", text: "Stop now" },
        { t: "list", items: [
          "Anything in the third group of the side-effects lesson. That is a clinician's call and the compound is already stopped by the time they are involved.",
          "A group-two side effect that returned after a dose reduction. The compound is wrong for this person, not the dose.",
          "Bloodwork that moved the wrong way past your baseline in a way the compound explains.",
          "A vial that failed a test, or a batch that other buyers have reported. Not worth the argument.",
        ] },
        { t: "h", text: "Stop at the end of the window" },
        { t: "list", items: [
          "A compound past its expected timeline with nothing in the log to show for it. The result is a result. Write it down and stop.",
          "A goal that has been reached. The injury healed, the tan is there, the season has passed. Continuing is habit.",
          "The end of a planned cycle, for the compounds where cycling has a mechanism.",
        ] },
        { t: "h", text: "How to stop" },
        { t: "p", text: "Almost every compound in this course can simply be stopped. The exceptions are worth knowing. The GLP-1s produce a return of appetite that people are better off planning for than surprised by, and some taper down the dose over a month or two. The growth hormone group is stopped outright; the pulses simply return to baseline. Nothing here produces a withdrawal syndrome in the sense a benzodiazepine or a steroid does." },
        { t: "h", text: "The difference between a side effect and a reason" },
        { t: "p", text: "A side effect is a cost, and costs are weighed. Nausea for three days at each GLP-1 step is a cost most people pay for the result. A reason is a cost that is not worth any result, or a sign that the compound is doing something other than what it should. Swollen hands are a cost that says lower the dose. A changing mole is a reason. The log, the timeline and the bloodwork are how the two are told apart." },
        { t: "note", text: "The habit that protects people: decide before starting what would make you stop, and write it at the top of the log. It is much easier to obey a rule you made calm than to make one mid-course." },
      ],
    },
  ],
};

export const MODULE_6 = {
  n: 6,
  slug: "staying-current",
  title: "Staying current",
  summary: "How to read a study, how to filter hype, and how the rules are changing.",
  status: "ready",
  lessons: [
    {
      slug: "reading-a-study",
      title: "Reading a study without a science degree",
      minutes: 12,
      free: false,
      summary: "Rats versus people, dose scaling, sample size, who funded it, and the abstracts that lie by omission.",
      body: [
        { t: "p", text: "Most claims in this market trace back to a real study. The claim is usually wrong anyway, because the study was in rats, or in twelve people, or measured something other than what the claim says. Reading the study takes ten minutes and does not require understanding the statistics. It requires six questions." },
        { t: "h", text: "The six questions" },
        { t: "list", items: [
          "Who was it in? Cells in a dish, animals, or people. Most peptide studies are the first two, and results do not transfer to people reliably. Rodent studies of drugs that later reached human trials fail in people far more often than they succeed.",
          "How many? A human study of twelve people can show a signal. It cannot show safety, and it cannot show that the signal was not chance. Look for the number in the methods, and be suspicious of anything under fifty presented as settled.",
          "Compared with what? A study with no placebo group measures the placebo effect plus the compound. For anything subjective, pain, mood, energy, the placebo effect is large.",
          "What was measured? A study that measured a blood marker is not a study of the outcome people want. IGF-1 going up is not muscle. Telomerase activity in a dish is not longer life.",
          "At what dose, and how was it given? Animal doses per kilogram are often many times what people use, and given by routes people do not use. A rat given a compound intraperitoneally at a large dose says little about a subcutaneous microgram dose in a person.",
          "Who paid? Manufacturer-funded studies are not wrong, but they are the ones where the outcome measure was chosen carefully. A study from the compound's developer with a marginal result is a marginal result.",
        ] },
        { t: "h", text: "Where the abstract lies by omission" },
        { t: "p", text: "Abstracts summarise the positive finding. They omit that it was one of eight outcomes measured, that it appeared in a subgroup, that it was at the highest dose only, or that the effect was statistically significant and clinically tiny. The habit that catches this is reading the results table, not the abstract, and asking whether the number in the table would change your behaviour if it were true." },
        { t: "h", text: "Where to read" },
        { t: "p", text: "PubMed indexes almost everything, and most abstracts are free. Many full papers are free through the journal or through the authors' institution. A vendor page that cites a study should link it; if the link goes to the vendor's own summary, that is the tell. The reference pages on this site list the key study for each compound, and the members' digest goes through new ones as they appear." },
        { t: "note", text: "A useful test for any claim: could the person making it tell you the number of people in the study and what was measured? If they can, listen. If they cannot, they read the abstract, or the vendor's summary of it." },
      ],
    },
    {
      slug: "hype-filters",
      title: "Hype filters",
      minutes: 8,
      free: false,
      summary: "The tells in an influencer post, a vendor page, and a forum thread.",
      body: [
        { t: "p", text: "Three sources produce most of what people believe about peptides, and each has a characteristic way of being wrong. Knowing the pattern is faster than checking every claim." },
        { t: "h", text: "The influencer post" },
        { t: "list", items: [
          "A transformation with a compound named and nothing else mentioned: no diet, no training, no other drugs. The compound is the sponsor, not the cause.",
          "A discount code. The recommendation is paid, and paid by a vendor whose product has not been tested by the person recommending it.",
          "Certainty. Nobody who has read the research on most of these compounds is certain about them. Certainty is a sales voice.",
          "Stacks of six compounds presented as a routine. A person taking six things cannot know what any of them does, and neither can their audience.",
        ] },
        { t: "h", text: "The vendor page" },
        { t: "list", items: [
          "Medical claims: heals, treats, cures, reverses. Either ignorant of the law or ignoring it, and either way not a source.",
          "A study cited with no link, or a link to the vendor's own summary.",
          "Certificates that all look the same. Module one.",
          "Perpetual discounts and countdown timers. Pricing theatre, and a sign the list price is fiction.",
          "The phrase research use only beside a page describing what it does in your body. The disclaimer and the copy are talking to different regulators.",
        ] },
        { t: "h", text: "The forum thread" },
        { t: "list", items: [
          "Dose ranges quoted with no source. They usually trace to one post years ago that everyone has repeated. The number may be fine; the confidence is inherited.",
          "The one person for whom it was miraculous. A single report proves the effect exists in one person, and nothing about how common it is.",
          "Advice that has not been updated for what has since been learned, particularly about the GLP-1s, where the picture has changed fast.",
          "The genuinely useful part: community test results, side-effect reports at scale, and vendors named for failing. Forums are best as a record of what went wrong, and worst as a guide to what to do.",
        ] },
        { t: "h", text: "The filter in one line" },
        { t: "p", text: "Who benefits if I believe this, and what would they have to show me for it to be true? A source that benefits and cannot show anything is marketing, whatever it is dressed as." },
      ],
    },
    {
      slug: "regulation",
      title: "How the rules are changing",
      minutes: 10,
      free: false,
      summary: "The 2023 compounding decision, the GLP-1 shortage and what ended it, and where enforcement is going.",
      body: [
        { t: "p", text: "The research-chemical market exists in the gap between what is legal to sell as a chemical and what is legal to sell as a medicine. That gap has been narrowing, and the direction matters for anyone relying on it." },
        { t: "h", text: "2023: the compounding decision" },
        { t: "p", text: "Compounding pharmacies had been a legitimate route to several of these compounds by prescription. In 2023 the FDA reviewed a list of substances nominated for compounding and placed BPC-157, along with several other peptides popular in this market, in a category it considers to carry significant safety risks, meaning pharmacies may not compound them. The stated reasoning was lack of data on human safety, not evidence of harm. The effect was to push demand from a prescription route to the research market, where the data problem is worse." },
        { t: "h", text: "2024 to 2025: the GLP-1 shortage ends" },
        { t: "p", text: "During the shortage of the branded semaglutide and tirzepatide products, compounders were permitted to make them, and a large telehealth industry grew on that permission. The FDA declared the tirzepatide shortage resolved in late 2024 and semaglutide in early 2025, and compounding of copies was wound down over the following months. Some telehealth sellers moved to modified formulations to stay in a grey zone; many customers moved to research-chemical vendors. This is why those two compounds now dominate the market, and why their counterfeiting is the biggest quality problem in it." },
        { t: "h", text: "What enforcement looks like" },
        { t: "list", items: [
          "Warning letters to sellers who make medical claims. This is the main tool and it is aimed at vendors, not buyers.",
          "Payment processor action. Not enforcement in the legal sense, but the thing that actually shuts vendors down, and the reason the payment shuffle from module one exists.",
          "Customs seizures of imported product, which affect vendors' supply and occasionally individual orders.",
          "Sport. WADA lists most of these compounds, and testing is the one place an individual user faces a direct consequence.",
        ] },
        { t: "h", text: "Where it is going" },
        { t: "p", text: "Two things are happening at once. Some compounds are becoming medicines: retatrutide is in late trials, elamipretide reached approval for a rare disease, and the GLP-1 class is becoming as routine as statins. As that happens, the prescription route for those compounds gets easier and the research market for them gets squeezed. At the same time, the compounds with no path to approval, which is most of the recovery and longevity group, are drifting further from any legitimate route, and pressure on the vendors who sell them is increasing. The likely shape of the next few years is a market that splits: prescription for what has data, and a smaller, more scrutinised grey market for what does not." },
        { t: "note", text: "The practical implication for a buyer is the one module one made: the only quality control in this market is the one you do yourself, and the amount of it required is going up, not down." },
      ],
    },
    {
      slug: "the-digest",
      title: "The members' digest",
      minutes: 4,
      free: false,
      summary: "How updates reach you, and how to ask a question about the material.",
      body: [
        { t: "p", text: "The evidence for most of these compounds is thin, which means it changes. A single good human trial moves a compound from one grade to another, a regulatory decision changes what is available, and a batch of community test results changes which vendors are worth trusting. The course would be out of date within a year if it were static, so it is not." },
        { t: "h", text: "What the digest is" },
        { t: "list", items: [
          "An email when something changes: a new study worth reading, graded and summarised the way the compound lessons are; a regulatory decision; a lesson that has been rewritten because the evidence moved.",
          "The changelog for the course, so members can see exactly what was updated and why.",
          "Community test results and vendor news, summarised without naming vendors as recommendations.",
          "Answers to members' questions about the material, written up where the answer is useful to everyone.",
        ] },
        { t: "h", text: "How to ask" },
        { t: "p", text: "Reply to any digest email. Questions about the material get answered: what a lesson meant, how to read a study, what a term means, whether a piece of news changes anything. That is the line, and it is worth restating: questions about a compound get an answer, and questions about you get pointed at a clinician, because that is the only honest answer to them." },
        { t: "h", text: "What founders get" },
        { t: "p", text: "Everything above, at no charge for the first year, and the founder price on the membership after that if they want to keep it. Every update to every lesson, for as long as the course exists, regardless." },
        { t: "note", text: "The most useful thing a member can send is a question that shows a lesson was unclear. Those turn into rewrites, and the rewrite is what the next reader gets." },
      ],
    },
  ],
};
