/**
 * Module 3: the peptides, by goal.
 *
 * Written for beginners. Every peptide follows the same seven headings so a
 * compound with forty years of medical use and one with three rat studies are
 * described in the same shape, and the difference is obvious. "How people
 * commonly use it" describes reported practice from trials and the community.
 * It is not a recommendation for anyone, and the lessons say so. Approved
 * medical doses are labeled as approved.
 */

export const MODULE_3 = {
  n: 3,
  slug: "the-compounds",
  title: "The peptides, by goal",
  summary: "Every peptide on the reference site, explained the same simple way: what it is, how good the evidence is, how people use it, what they notice, side effects, and who stays away from it.",
  status: "ready",
  lessons: [
    {
      slug: "how-to-read-these-pages",
      title: "How to read these pages",
      minutes: 5,
      free: true,
      summary: "The seven headings, what \"commonly used\" means, and the A-to-D evidence grades.",
      body: [
        { t: "p", text: "Every peptide in this module is written under the same seven headings. That way a peptide with decades of medical use and one with three rat studies get described in the same shape, and you can see the difference instead of having it hidden in the writing." },
        { t: "h", text: "The seven headings" },
        { t: "list", items: [
          "What it is. The molecule, where it came from, and what it tells the body to do, in one plain paragraph.",
          "The evidence, graded. See the grades below.",
          "How people commonly use it. The doses, routes, timing and lengths that show up in medical trials where they exist, and in community practice where they don't. Approved medical doses are marked as approved. Nothing under this heading is a recommendation for you.",
          "What people notice. The real experience, including the very common experience of nothing at all.",
          "Side effects. The usual ones, the rare ones, and the ones that mean stop.",
          "Interactions. Medications and health conditions where the overlap is real.",
          "Who stays away from it. Not a medical judgment. The groups for whom the reported downside is worst.",
        ] },
        { t: "h", text: "The evidence grades" },
        { t: "list", items: [
          "A. Approved as a medicine somewhere, with big controlled trials behind it. What it does at the approved dose is known. What it does at other doses, in other people, for other reasons, is not.",
          "B. Tested in people, but not approved for the thing people buy it for. We know something about safety in humans. The claims usually run ahead of the data.",
          "C. Tested only in animals or cells. Everything about human use is an educated guess. This is most of the market.",
          "D. Stories and vendor copy. Nothing here should be called evidence.",
        ] },
        { t: "fig", id: "evidence-ladder", caption: "The four grades, with examples. Most of the market is C." },
        { t: "note", text: "A grade is about the evidence for the popular use, not the peptide itself. Semaglutide is grade A for weight loss and grade C for the anti-aging claims some people make about it. Where one peptide has several uses at different grades, the lesson says which is which." },
        { t: "warn", text: "Dose ranges here are reported, not endorsed. They're included because leaving them out would send you to a forum to find them, which is worse. Several of these peptides change hormones, blood sugar or blood pressure. Module five is the safety material, and it applies to everything in this module." },
      ],
    },
    {
      slug: "recovery-and-repair",
      title: "Recovery and repair",
      minutes: 25,
      free: false,
      summary: "BPC-157, TB-500 and the Wolverine blend: the peptides athletes reach for first, and the gap between the hype and the evidence.",
      body: [
        { t: "p", text: "If you've heard of any peptide, it's probably one of these. They're the best-selling compounds in the market and the ones athletes talk about most, for tendons, joints, muscle pulls and nagging injuries. They're also the ones with the biggest gap between how confidently people discuss them and how much is actually known. The animal research is genuinely impressive. The human research barely exists. Both things are true, and this lesson holds both." },

        { t: "h", text: "BPC-157" },
        { t: "card", name: "BPC-157", grade: "C", route: "Under the skin, or swallowed for gut use", often: "Once or twice daily", length: "4 to 8 weeks, or the length of an injury", wada: "Banned", note: "Best-selling recovery peptide. Animal evidence only for injuries." },
        { t: "p", text: "What it is. A small piece of a protein found naturally in your stomach juices, made in a lab. In animals it seems to boost blood vessel growth and repair signals, which is why it shows up in studies of tendon, muscle, gut and nerve injuries. Unusually for a peptide, it survives stomach acid, so some people swallow it instead of injecting it." },
        { t: "p", text: "The evidence: C for injuries and gut, with a footnote. Hundreds of rat and mouse studies, mostly from one research group in Croatia, show faster healing of tendons, ligaments, muscles and gut damage. A drug company version got as far as early human trials for a bowel disease a decade ago and was never taken further. There are no published controlled trials in people for injuries. In 2023 the FDA blocked pharmacies from compounding it, citing unknowns about safety rather than known harm." },
        { t: "p", text: "How people commonly use it. Reported injections under the skin of 200 to 500 micrograms, once or twice a day, for four to eight weeks, often injected near the injury on the belief that it works locally. For gut problems, capsules or drops under the tongue are reported at similar daily amounts. Some people run it continuously. Most use it for the length of an injury." },
        { t: "p", text: "What people notice. Tendon and soft-tissue pain easing faster than expected, usually within two to four weeks, is the most common report. Gut relief is the second. A good number of people report nothing, which is worth taking seriously given how unreliable the dosing is and how strongly pain responds to expectation." },
        { t: "p", text: "Side effects. Reported as mild and uncommon: nausea, dizziness, headache, irritation at the injection site. The theoretical worry is that a peptide which grows blood vessels could feed a tumor that already exists. No human case has proven this. No human trial has ruled it out." },
        { t: "p", text: "Interactions. Nothing well documented. Because it affects the same signaling as some blood-pressure drugs, people on those sometimes feel light-headed." },
        { t: "p", text: "Who stays away. Anyone with a current or recent cancer, for the blood-vessel reason. Pregnant women. And anyone in a drug-tested sport: BPC-157 is banned by WADA." },

        { t: "h", text: "TB-500" },
        { t: "card", name: "TB-500", grade: "C", route: "Under the skin", often: "Twice a week, then monthly", length: "4 to 6 week load, then maintenance", wada: "Banned", note: "Much of what is sold is the full thymosin beta-4 molecule." },
        { t: "p", text: "What it is. A short piece of thymosin beta-4, a protein found in almost every cell in your body that helps cells move around. The idea is that it helps repair cells travel to damaged tissue and calms inflammation there. One thing beginners should know: a lot of what's sold as TB-500 is actually the full thymosin beta-4 molecule, not the fragment, and vendors rarely say which." },
        { t: "p", text: "The evidence: C for injuries, B for two narrow uses. Lots of animal work on heart, skin and eye injuries, including a well-known 2004 study on heart cells in mice. The full molecule has been through human trials for dry eye and chronic wounds, with mixed results. For the muscle and tendon uses people buy it for, there's no controlled human data." },
        { t: "p", text: "How people commonly use it. A \"loading\" period of roughly 2 to 2.5 milligrams twice a week for four to six weeks, then a similar dose once or twice a month. It's taken less often than BPC-157 because it's believed to stay in tissue long after it leaves the blood. Injected under the skin, not necessarily near the injury." },
        { t: "p", text: "What people notice. Better flexibility and less stiffness get reported more than outright healing. Some describe a brief head rush or tiredness after a dose. Like BPC-157, plenty of people report nothing they can pin on it." },
        { t: "p", text: "Side effects. Head rush, brief fatigue, injection-site reactions. The same theoretical concern about encouraging growth where it shouldn't happen." },
        { t: "p", text: "Who stays away. Current or recent cancer. Tested athletes, since it's WADA-banned. And anyone who isn't comfortable with a product whose vendors don't always say which molecule is in the vial." },

        { t: "h", text: "The Wolverine blend" },
        { t: "card", name: "The Wolverine blend", grade: "C", route: "Under the skin", often: "Daily or every other day", length: "4 to 8 weeks", wada: "Banned", note: "Two peptides, one vial. Convenient, and untestable." },
        { t: "p", text: "What it is. BPC-157 and TB-500 in one vial, usually in equal amounts. The logic is that they work in different ways, one on blood vessels and local signaling, the other on cell movement, so together they might cover more. There's no study of the combination. Its popularity comes from the market, not the science." },
        { t: "p", text: "How people commonly use it. Daily or every-other-day injections that deliver a few hundred micrograms of BPC-157 alongside a few hundred micrograms to a milligram of TB-500, for four to eight weeks. Because the two are normally taken on different schedules, a blend forces a compromise on one of them." },
        { t: "p", text: "The trade-off to understand. A blend is convenient, and it breaks the most important rule in module four: change one thing at a time. If the blend helps, you don't know which half did it. If it causes a side effect, you don't know which half to stop. People who want to learn what works for them run the two separately first, and blend later once they know." },
        { t: "warn", text: "Everything in this lesson rests on animal evidence for the things people buy it for. That's not a reason to dismiss it, and it's not a reason to treat forum confidence as proof. If you have an injury that isn't getting better, you need a real diagnosis before any of this is relevant." },
      ],
    },
    {
      slug: "growth-hormone-axis",
      title: "The growth hormone peptides",
      minutes: 30,
      free: false,
      summary: "Ipamorelin, CJC-1295, sermorelin, tesamorelin. How they nudge your body to make more of its own growth hormone, and the blood-sugar catch.",
      body: [
        { t: "p", text: "Growth hormone is what your body uses to repair, build and recover, and you make less of it every year after your twenties. The peptides in this lesson don't give you growth hormone. They ask your own pituitary gland, a pea-sized organ at the base of the brain, to release more of what it already makes. That's the whole point of the category, and why people choose it over synthetic growth hormone: your body's own safety limits stay in charge." },
        { t: "h", text: "The two switches" },
        { t: "list", items: [
          "Switch one, the GHRH copies. Sermorelin, both kinds of CJC-1295, and tesamorelin all mimic the natural hormone that tells the pituitary \"release growth hormone now.\" They make each release bigger.",
          "Switch two, the ghrelin copies. Ipamorelin is the one on this site. Ghrelin is your hunger hormone, and it also triggers growth hormone release through a different door. Ipamorelin opens that door while also quieting the hormone that would normally shut the release down.",
          "Pressing both switches at once produces a bigger release than either alone. That's why the CJC-plus-ipamorelin blend exists and why it's the most common combination.",
        ] },
        { t: "h", text: "Pulses versus a steady drip" },
        { t: "p", text: "Your body releases growth hormone in bursts, with the biggest one in the first hours of sleep. The short-acting peptides copy that: a dose before bed makes a burst, then levels fall back. CJC-1295 \"with DAC\" is the exception. It attaches to a protein in your blood and keeps growth hormone raised for about a week per dose. That's convenient, and it turns the natural bursts into a steady drip people call a \"bleed.\" The argument against it is that a steady drip is further from how the body works and more likely to cause the side effects listed below. Whether that matters at the doses people use isn't settled." },

        { t: "fig", id: "pulses", caption: "Natural growth hormone comes in bursts. Short-acting peptides copy that. The DAC version flattens it into a week-long plateau." },
        { t: "h", text: "Ipamorelin" },
        { t: "card", name: "Ipamorelin", grade: "B", route: "Under the skin, empty stomach", often: "1 to 3 times daily, always one before bed", length: "8 to 12 weeks, then a break", wada: "Banned", note: "The cleanest growth hormone trigger. Sleep changes come first." },
        { t: "p", text: "What it is. A five amino acid ghrelin copy from the 1990s. It's preferred over older peptides in its class because it triggers growth hormone without meaningfully raising cortisol (the stress hormone) or prolactin, which the older ones did." },
        { t: "p", text: "The evidence: B. Human studies show it reliably produces a growth hormone burst. It was developed toward a use after surgery that never got approved. There are no controlled trials for the muscle, sleep or recovery uses people buy it for." },
        { t: "p", text: "How people commonly use it. Injections under the skin of 100 to 300 micrograms, one to three times a day, with a dose before bed being the constant. Taken on an empty stomach, because food, especially carbs and fat, blunts the burst. Usually run for eight to twelve weeks, then paused." },
        { t: "p", text: "What people notice. Deeper sleep and vivid dreams, often within the first week, are the most consistent report. Better recovery from training and a slow shift toward less fat and more muscle over months come next. Some hunger after a dose, though much less than with older peptides of this type." },

        { t: "h", text: "CJC-1295 without DAC" },
        { t: "card", name: "CJC-1295 without DAC", grade: "B", route: "Under the skin, empty stomach", often: "With ipamorelin, 1 to 3 times daily", length: "8 to 12 weeks, then a break", wada: "Banned", note: "Makes each growth hormone burst bigger. Wears off in about 30 minutes." },
        { t: "p", text: "What it is. A modified copy of the first 29 building blocks of the natural growth hormone releasing hormone, tweaked to last longer in the blood than sermorelin. Also sold as \"Mod GRF 1-29.\" It wears off in about half an hour." },
        { t: "p", text: "The evidence: B. Human data exists from when it was developed. No trials for the uses it's bought for." },
        { t: "p", text: "How people commonly use it. Almost always paired with ipamorelin, at roughly 100 micrograms of each per dose, one to three times daily on the same empty-stomach, before-bed pattern. On its own it's used the same way, just less often." },

        { t: "h", text: "CJC-1295 with DAC" },
        { t: "card", name: "CJC-1295 with DAC", grade: "B", route: "Under the skin", often: "Once a week", length: "8 to 12 weeks, then a break", wada: "Banned", note: "Lasts about a week. Convenient; flattens the natural bursts." },
        { t: "p", text: "What it is. The same molecule with an extra piece attached (the \"DAC\") so it clings to a blood protein and lasts about eight days." },
        { t: "p", text: "The evidence: B. A 2006 human study showed growth hormone and its downstream marker, IGF-1, stayed raised for a week or more after one dose." },
        { t: "p", text: "How people commonly use it. Reported at 1 to 2 milligrams once a week. Chosen for convenience. Avoided by people who care about keeping the natural bursts, for the reason above." },

        { t: "h", text: "Sermorelin" },
        { t: "card", name: "Sermorelin", grade: "A / B", route: "Under the skin at bedtime", often: "Nightly", length: "Months", wada: "Banned", note: "The one with a prescription route. Weakest per dose." },
        { t: "p", text: "What it is. The natural releasing hormone, unmodified. The oldest peptide in this group. It was FDA-approved in 1997 for children who don't make enough growth hormone, then withdrawn for business reasons, not safety. It's still available from compounding pharmacies with a prescription, which makes it the one peptide here with a legitimate non-research route." },
        { t: "p", text: "The evidence: A for growth hormone deficiency, B for the normal decline of aging. Decades of clinical use. Trials in older adults show modest gains in lean mass and some sleep changes, with the side effects below as the cost." },
        { t: "p", text: "How people commonly use it. Clinics prescribe 200 to 500 micrograms under the skin at bedtime for several months, and research-market use copies that. Because it wears off in ten to twenty minutes, it's the weakest option per dose." },

        { t: "h", text: "Tesamorelin" },
        { t: "card", name: "Tesamorelin", grade: "A / B", route: "Under the skin at night", often: "Daily", length: "3 to 6 months in trials", wada: "Banned", note: "FDA-approved for belly fat in one group. The expensive one." },
        { t: "p", text: "What it is. A stabilized copy of the releasing hormone, and the only peptide in this lesson that is FDA-approved right now, for reducing belly fat in people with HIV whose medication causes fat buildup. That approval means a full safety record exists." },
        { t: "p", text: "The evidence: A for belly fat in that group, B for belly fat and liver fat in everyone else, and B for the memory findings in older adults that get quoted. The approved dose is 2 milligrams under the skin once a day. Trials in people without HIV have shown less liver fat." },
        { t: "p", text: "How people commonly use it. The approved dose, or 1 to 2 milligrams daily, usually at night. It's by far the most expensive peptide in the group, which is why the tesamorelin-plus-ipamorelin blend is sold as a premium option rather than a default." },

        { t: "h", text: "Side effects across the whole group" },
        { t: "list", items: [
          "Water retention, and with it tingling or numb hands that feel like carpal tunnel. The most common complaint, gets worse with dose, and it's the first sign someone is taking more than they need.",
          "Blood sugar. Growth hormone works against insulin, so fasting blood sugar can creep up. People who are already prediabetic or diabetic notice it first. This is the interaction that matters most.",
          "Headache, flushing and injection-site reactions in the first days, usually fading.",
          "Hunger, especially with the ghrelin copies, though ipamorelin is the mildest.",
          "Achy joints with continuous elevation, reported more with the DAC version.",
        ] },
        { t: "h", text: "Interactions, and who stays away" },
        { t: "list", items: [
          "Diabetes or insulin resistance, for the blood sugar reason. Anyone on insulin or a drug that lowers blood sugar is in territory that needs a clinician.",
          "Active cancer. Growth hormone and IGF-1 are growth signals, and this is the one group where everyone takes the theoretical risk seriously.",
          "Thyroid problems. Growth hormone changes how thyroid hormones convert and can reveal an underactive thyroid.",
          "Pregnancy. And anyone under about 25, whose body is still doing this on its own.",
          "Drug-tested athletes. All of these are WADA-banned.",
          "Bloodwork people run: IGF-1 to see if it's working, fasting blood sugar or HbA1c to see what it's costing. Module five covers timing.",
        ] },
        { t: "note", text: "The practical pattern most experienced users land on: a short-acting releasing peptide plus ipamorelin, before bed, on an empty stomach, in eight to twelve week blocks, with IGF-1 and blood sugar checked. Everything else in this lesson is a variation on that." },
      ],
    },
    {
      slug: "metabolic",
      title: "Weight loss and metabolism",
      minutes: 30,
      free: false,
      summary: "Semaglutide, tirzepatide, retatrutide, AOD-9604. The famous weight-loss shots, why the slow ramp-up matters, the muscle-loss issue, and what changed in the market.",
      body: [
        { t: "p", text: "This is the one category where the peptides are real, mainstream medicine. Two of the four are FDA-approved drugs backed by the biggest weight-loss trials ever run. That changes what the research-chemical version is: the same molecule, without the manufacturing checks, without a doctor, and without the careful ramp-up schedule the trials used to keep people safe. Most of this lesson is about that schedule." },

        { t: "h", text: "Semaglutide" },
        { t: "card", name: "Semaglutide", grade: "A", route: "Under the skin", often: "Once a week", length: "Long-term; stopping brings appetite back", wada: "Not banned", note: "The drug in Ozempic and Wegovy. The ramp-up schedule is the safety mechanism." },
        { t: "p", text: "What it is. A copy of a gut hormone called GLP-1. It slows your stomach down, tells your brain you're full, and helps your body handle sugar. Sold as Ozempic for diabetes and Wegovy for weight. One injection a week, and it lasts about a week in the body." },
        { t: "p", text: "The evidence: A. The big trials showed about 15% body weight lost over 68 weeks at the top dose, against about 2.5% for the fake version. A separate large trial showed it protects the heart. This is as good as evidence gets in this course." },
        { t: "p", text: "How people commonly use it. The approved schedule starts at 0.25 milligrams once a week for four weeks, then 0.5, then 1, then 1.7, then 2.4, each step held for at least four weeks. The schedule exists because the stomach side effects depend on the dose and your body needs time to adjust. Research-market use copies the schedule when it goes well and skips steps when it doesn't. Skipping steps is where most of the vomiting comes from." },

        { t: "fig", id: "titration", caption: "Why the ramp-up exists. Each step gives the stomach time to adjust before the next." },
        { t: "h", text: "Tirzepatide" },
        { t: "card", name: "Tirzepatide", grade: "A", route: "Under the skin", often: "Once a week", length: "Long-term; stopping brings appetite back", wada: "Not banned", note: "Beat semaglutide head to head. Same rule about the schedule." },
        { t: "p", text: "What it is. Hits two gut-hormone switches at once: GLP-1 and a second one called GIP. Sold as Mounjaro and Zepbound. Weekly injection, lasts about five days." },
        { t: "p", text: "The evidence: A. The big trial showed about 21% body weight lost at the highest dose over 72 weeks, and a 2024 head-to-head trial found it beat semaglutide directly." },
        { t: "p", text: "How people commonly use it. The approved schedule starts at 2.5 milligrams weekly for four weeks, then goes up in 2.5 milligram steps to a maximum of 15, each held four weeks or more. Same rule: the schedule is the safety mechanism." },

        { t: "h", text: "Retatrutide" },
        { t: "card", name: "Retatrutide", grade: "B", route: "Under the skin", often: "Once a week", length: "Not established; in final trials", wada: "Not banned", note: "Biggest weight loss ever reported. Long-term safety unknown." },
        { t: "p", text: "What it is. Hits three switches, adding glucagon to the other two, which is thought to burn more energy and clear fat from the liver. Not approved anywhere yet. In the final stage of trials." },
        { t: "p", text: "The evidence: B, on its way to A. A 2023 mid-stage trial showed about 24% weight lost at 48 weeks at the top dose, the biggest number any drug has produced, and the large final trials are running now. Long-term safety isn't known yet. That's what the final trials are for." },
        { t: "p", text: "How people commonly use it. There's no approved dose, and that's the point. Research-market users report weekly doses starting around 1 to 2 milligrams and climbing toward the trial's 8 to 12 milligram range over months. Everyone using it outside a trial is doing the trial's job without the monitoring. Faster heart rate was a notable finding in the trials and is the thing to watch." },

        { t: "h", text: "AOD-9604" },
        { t: "card", name: "AOD-9604", grade: "C", route: "Under the skin", often: "Daily", length: "Weeks", wada: "Not banned", note: "Failed its own human trials for weight loss." },
        { t: "p", text: "What it is. A small piece of growth hormone, meant to keep the fat-burning signal without the growth and blood-sugar effects of the whole hormone." },
        { t: "p", text: "The evidence: C for weight loss, with a history worth knowing. The company that developed it ran human trials in the 2000s. They failed to show meaningful weight loss and the company dropped it. It later got a food-safety designation in the US, which vendors present as approval. It isn't. It means eating small amounts is safe." },
        { t: "p", text: "How people commonly use it. Reported at 250 to 500 micrograms under the skin daily, often in the morning before a workout. The honest summary: the human trials were the test, and it didn't pass." },

        { t: "h", text: "What people notice, across the GLP-1 group" },
        { t: "p", text: "Appetite drops within the first week or two, sometimes completely. \"Food noise,\" the constant background thinking about eating, goes quiet, and many people describe that as the real effect. Weight comes off at roughly a pound or two a week once at a steady dose. Less interest in alcohol is reported often enough that it's being studied. Tiredness in the early weeks is common." },
        { t: "h", text: "Side effects" },
        { t: "list", items: [
          "Nausea, vomiting, constipation or diarrhea. Most people get some. It depends on the dose, it's worst in the days after a step up, and it's the reason the schedule exists.",
          "Muscle loss. Losing weight fast takes muscle with it, and the trials found a meaningful share of the weight lost wasn't fat. Strength training and enough protein are the standard answer, and the most-discussed topic among long-term users. For an athlete, this is the side effect that matters most.",
          "Gallbladder problems and, rarely, inflammation of the pancreas. Severe, lasting belly pain means stop and see someone.",
          "The stomach slowing down so much it becomes a problem in some people, and a known issue with anesthesia. Surgeons now ask about these drugs.",
          "A thyroid tumor warning based on rat studies, which means people with a personal or family history of a certain thyroid cancer (medullary) or a syndrome called MEN2 shouldn't use them.",
          "Rebound. Stop, and appetite comes back. Most trial participants regained most of the weight within a year. This is a long-term drug, and the cost of buying it for years is part of the decision.",
        ] },
        { t: "h", text: "Interactions, and who stays away" },
        { t: "list", items: [
          "Insulin and certain diabetes pills: risk of blood sugar going too low. This needs a doctor managing both.",
          "Any pill that needs steady absorption. A slower stomach changes how pills get absorbed. Thyroid medication and the birth-control pill are the ones people notice.",
          "Personal or family history of medullary thyroid cancer or MEN2. Pregnancy, or planning it: these are stopped months before.",
          "History of pancreatitis or gallbladder disease. Eating disorders. Anyone already at a low body weight.",
        ] },
        { t: "h", text: "What changed in the market" },
        { t: "p", text: "For a couple of years, pharmacies were allowed to make copies of semaglutide and tirzepatide because the brand-name drugs were in shortage. The FDA declared the tirzepatide shortage over in late 2024 and semaglutide in early 2025, and the copies were phased out. The people buying from those pharmacies didn't stop wanting the drug, and a big share moved to research-chemical vendors. That's why these two peptides now dominate vendor sales, and why module one matters most here: a GLP-1 vial is the most-faked product in this market." },
        { t: "warn", text: "Of everything in this course, these are the peptides where going without a doctor is hardest to defend. A prescription route exists, the drugs are powerful, and the side effects can be serious. This lesson explains them because people use them either way. It doesn't make that a good idea." },
      ],
    },
    {
      slug: "longevity-and-mitochondria",
      title: "Longevity and cellular energy",
      minutes: 20,
      free: false,
      summary: "SS-31, MOTS-c, NAD+, epithalon, pinealon. The biggest claims in the market, the thinnest evidence, and the one that became a real medicine.",
      body: [
        { t: "p", text: "This is the category with the biggest promises and, with one exception, the thinnest evidence. The exception is a peptide that has now become an approved drug for a rare disease, which is worth understanding because it shows what the others would need to become to earn their reputations. Most of these act on mitochondria, the tiny power plants inside every cell, which slow down as you age." },

        { t: "h", text: "SS-31 (elamipretide)" },
        { t: "card", name: "SS-31 (elamipretide)", grade: "A / B", route: "Under the skin", often: "Daily", length: "4 to 8 weeks", wada: "Not banned", note: "Approved in 2025 for one rare disease. Unproven in healthy people." },
        { t: "p", text: "What it is. A four amino acid peptide that goes straight into mitochondria and stabilizes the machinery that makes energy. A drug company spent two decades developing it." },
        { t: "p", text: "The evidence: A for one rare disease, B for everything else. After years of trials in heart failure, eye disease and muscle disease that mostly missed their goals, it was approved in the US in 2025 for Barth syndrome, a rare inherited mitochondrial disease. Trials in age-related conditions showed hints without clear wins. For the general anti-aging or performance use, what we know is that it's safe enough to have been given to thousands of trial participants, and that its effects in healthy people are unproven." },
        { t: "p", text: "How people commonly use it. Reported at 5 to 10 milligrams under the skin daily, in blocks of four to eight weeks. Injection-site reactions are the main complaint, in trials and in practice." },

        { t: "h", text: "MOTS-c" },
        { t: "card", name: "MOTS-c", grade: "C", route: "Under the skin", often: "2 to 3 times a week", length: "4 to 6 weeks", wada: "Not banned", note: "Impressive in mice. The human version failed its trial." },
        { t: "p", text: "What it is. A peptide your mitochondria release during exercise, which switches on the body's metabolic housekeeping. It's called \"exercise in a molecule\" because of what it does in mice." },
        { t: "p", text: "The evidence: C, with a failed human attempt. A 2020 mouse study showed better physical performance and metabolic protection. A drug-company version was tested in people for fatty liver and obesity, didn't meet its goals, and the company stopped. That leaves animal data for the use people buy it for." },
        { t: "p", text: "How people commonly use it. Reported at 5 to 10 milligrams under the skin two or three times a week for four to six weeks, often before training. People report better endurance and less fatigue. Some report nothing. Reported side effects are minor and local." },

        { t: "h", text: "NAD+" },
        { t: "card", name: "NAD+", grade: "B / C", route: "Under the skin, or IV drip in clinics", often: "Daily to a few times a week", length: "Weeks", wada: "Not banned", note: "Not a peptide. Pills your body converts are cheaper and better studied." },
        { t: "p", text: "What it is. Not a peptide at all. A molecule every cell uses to make energy and repair DNA, which declines with age. Sold as a powder for injection and given by IV drip in wellness clinics." },
        { t: "p", text: "The evidence: B for the pills that your body turns into NAD+, C for injecting NAD+ itself. Oral \"precursors\" like NR and NMN have small human trials with mixed, modest results. Injected NAD+ has almost no controlled human data. Its popularity comes from clinic marketing." },
        { t: "p", text: "How people commonly use it. Under the skin, 50 to 100 milligrams daily or several times a week, or IV drips of several hundred milligrams in clinics. Run into a vein too fast it causes chest tightness, flushing, cramping and nausea, which is why clinics take hours to do it. Injecting it under the skin is reported as painful. People report energy and clarity, which is also what people report from an afternoon in a comfortable clinic chair." },

        { t: "h", text: "Epithalon" },
        { t: "card", name: "Epithalon", grade: "C", route: "Under the skin", often: "Daily", length: "10 to 20 days, once or twice a year", wada: "Not banned", note: "Russian bioregulator. You will not feel it working." },
        { t: "p", text: "What it is. A four amino acid copy of an extract from the pineal gland, from a Russian research program that produced a whole family of short peptides they call \"bioregulators.\" Proposed to protect the ends of your chromosomes and regulate melatonin, the sleep hormone." },
        { t: "p", text: "The evidence: C, with a catch about where the human data is. Lab studies from 2003 showed it activates a DNA-protecting enzyme in human cells. Russian trials in elderly people reported fewer deaths over years, but they're old, from one group, and never repeated elsewhere. Outside that program there's essentially nothing." },
        { t: "p", text: "How people commonly use it. Reported at 5 to 10 milligrams under the skin daily for ten to twenty days, once or twice a year. The short course and long gap come from the original Russian protocols. Reported side effects are rare and minor. People report better sleep during a course and little else they can point to, which makes sense for a peptide whose supposed effect is on a decades-long process." },

        { t: "h", text: "Pinealon" },
        { t: "card", name: "Pinealon", grade: "C", route: "Under the skin", often: "Daily", length: "10 to 20 days, once or twice a year", wada: "Not banned", note: "Same family as epithalon, thinner evidence." },
        { t: "p", text: "What it is. A three amino acid peptide from the same Russian program, proposed to protect brain cells." },
        { t: "p", text: "The evidence: C, and thin even for this lesson. Animal and lab studies from the originating group." },
        { t: "p", text: "How people commonly use it. The same short-course pattern as epithalon, often alongside it. Almost no side effects reported, and almost no effects reported either." },

        { t: "h", text: "Why people cycle these" },
        { t: "p", text: "None of these peptides has a natural feedback system to protect, the way the growth hormone group does. Cycling in this category comes from the Russian protocols and from caution: with compounds whose long-term effects in humans are unknown, using them for limited periods with long gaps is the sensible default. It isn't a rule derived from evidence, because the evidence to derive it from doesn't exist." },
        { t: "note", text: "An honest ranking for someone choosing one: SS-31 has the most human safety data. NAD+ precursors taken as pills are the cheapest and best studied of the NAD options. Everything else here is a bet on animal data, and the bet is small money for probably nothing rather than any documented harm." },
      ],
    },
    {
      slug: "skin-and-hair",
      title: "Skin, hair and looks",
      minutes: 15,
      free: false,
      summary: "GHK-Cu and the Glow and Klow blends. Cream versus injection, and what the copper is doing.",
      body: [
        { t: "h", text: "GHK-Cu" },
        { t: "card", name: "GHK-Cu", grade: "B / C", route: "Cream (best evidence), or under the skin", often: "Daily", length: "Cream: indefinitely. Injected: 4 to 6 weeks", wada: "Not banned", note: "The cream has human trials. The injection stings and has none." },
        { t: "p", text: "What it is. A three amino acid peptide attached to a copper atom. Your blood is full of it when you're young and has very little by your sixties. In lab and animal studies it increases collagen (the protein that keeps skin firm), helps wounds heal, and switches on a large number of repair genes. The copper is part of how it works, not decoration." },
        { t: "p", text: "The evidence: B for creams, C for injections. The cosmetics research includes small controlled human trials of GHK-Cu creams showing thicker, firmer skin and shallower wrinkles, which is why it's in skincare products. Injecting it for whole-body anti-aging or hair growth has no human trials." },
        { t: "p", text: "How people commonly use it. As a cream or serum at about 1 to 3 percent, daily, indefinitely. Injected, reported at 1 to 2 milligrams under the skin daily for four to six weeks, sometimes near the area of interest. For hair, it's often applied to the scalp as a liquid rather than injected." },
        { t: "p", text: "What people notice. From the cream: smoother skin over months, matching the trials. From injecting: the most consistent report is that it stings badly at the injection site, followed by better skin and hair over weeks that's hard to separate from other changes." },
        { t: "p", text: "Side effects. Injection-site pain is nearly universal and is why many people switch to the cream. Brief drops in blood pressure and light-headedness are reported at higher injected doses. Copper is a metal the body manages carefully, and sustained high-dose injection is an unstudied load." },
        { t: "p", text: "Interactions, and who stays away. Wilson's disease or any condition affecting how the body handles copper. Anyone on blood-pressure medication who notices dizziness. Otherwise little documented." },

        { t: "h", text: "The Glow blend" },
        { t: "card", name: "The Glow blend", grade: "C", route: "Under the skin", often: "Daily", length: "4 to 6 weeks", wada: "Banned", note: "GHK-Cu plus the recovery pair. Three peptides, one vial." },
        { t: "p", text: "What it is. GHK-Cu plus BPC-157 and TB-500 in one vial: the recovery pair plus the collagen peptide. Marketed for skin and healing together." },
        { t: "p", text: "How people commonly use it. Daily injections under the skin delivering about a milligram of GHK-Cu alongside a few hundred micrograms of each recovery peptide, for four to six weeks. Same trade-off as every blend: three peptides, three sets of possible side effects, one vial, no way to tell which did what." },

        { t: "h", text: "The Klow blend" },
        { t: "card", name: "The Klow blend", grade: "C", route: "Under the skin", often: "Daily", length: "4 to 6 weeks", wada: "Banned", note: "Glow plus KPV. Four peptides is a way of not deciding." },
        { t: "p", text: "What it is. Glow plus KPV, the anti-inflammatory peptide covered in the immune lesson. Marketed as a four-way healing blend for skin, gut and inflammation." },
        { t: "p", text: "How people commonly use it. Like Glow, with a few hundred micrograms of KPV alongside. Four peptides in one vial is where most careful users stop and ask what they're actually trying to fix, because a blend this broad is a way of not deciding." },
        { t: "note", text: "The cheapest version of everything in this lesson is a GHK-Cu cream, which has the only human trials in the category. Injecting adds cost, pain and uncertainty, and removes the evidence." },
      ],
    },
    {
      slug: "cognition-and-mood",
      title: "Focus, mood and brain health",
      minutes: 18,
      free: false,
      summary: "Selank, semax, cerebrolysin. Three peptides that are real medicines in Russia and elsewhere, sold here without the context.",
      body: [
        { t: "p", text: "All three peptides here are approved medicines somewhere other than the United States. That puts them in an unusual spot: real human data exists, in languages and journals most English-speaking buyers never read, and the research market sells them with none of that context." },

        { t: "h", text: "Selank" },
        { t: "card", name: "Selank", grade: "A / B", route: "Nasal drops or spray", often: "1 to 3 times a day, as needed", length: "A few weeks, or as needed", wada: "Not banned", note: "Approved in Russia for anxiety. Calm without drowsiness." },
        { t: "p", text: "What it is. A seven amino acid copy of an immune peptide, developed in Russia as an anti-anxiety medicine and approved there as nasal drops. It's thought to work on the brain's calming system and boost BDNF, a growth factor that helps brain cells." },
        { t: "p", text: "The evidence: A in Russia for anxiety, effectively B elsewhere because the trials were never repeated outside that system. Russian controlled trials reported anxiety relief comparable to a benzodiazepine (a Xanax-type drug) without the drowsiness or dependence. No Western trials." },
        { t: "p", text: "How people commonly use it. Up the nose, as drops or spray, 250 to 500 micrograms one to three times a day. That's how it was developed and prescribed. Injecting it under the skin at similar doses is also reported. The effect is described as lasting well beyond the peptide's short life in the body, up to a day or more. Used as needed, or in courses of a few weeks." },
        { t: "p", text: "What people notice. A calm, clear feeling without drowsiness, usually within an hour. Some report better focus. Plenty report nothing. Tolerance with daily use is reported often enough to explain why courses are kept short." },
        { t: "p", text: "Side effects. Fatigue and low mood in some users, nasal irritation, and little else documented. Interactions aren't well studied. Not mixing it with sedatives or alcohol is the common-sense caution." },

        { t: "h", text: "Semax" },
        { t: "card", name: "Semax", grade: "A / B", route: "Nasal drops or spray, mornings", often: "Daily", length: "10 days to a few weeks", wada: "Not banned", note: "Approved in Russia for stroke recovery. Focus and drive, same-day." },
        { t: "p", text: "What it is. A piece of a stress hormone with a modification, from the same Russian program. Approved there for stroke recovery and memory problems. Thought to raise the brain's growth factors and sharpen attention." },
        { t: "p", text: "The evidence: A in Russia for stroke, B elsewhere. Russian trials in stroke patients and in people with memory complaints reported benefit. A 2014 study found it changes the activity of a large number of genes in brain tissue, which is quoted as its mechanism and really means it does a lot of things at once. No Western trials." },
        { t: "p", text: "How people commonly use it. Up the nose, 200 to 600 micrograms in the morning, in courses of ten days to a few weeks. Stronger variants are sold at lower doses. Injecting is uncommon." },
        { t: "p", text: "What people notice. Better focus and drive within the hour, sometimes with irritability. Wears off the same day. Reports of hair shedding during extended use circulate widely with no published basis, but come up often enough to mention." },
        { t: "p", text: "Side effects. Irritability, agitation, headache, and a rise in blood pressure in some users, which is the interaction that matters for anyone with high blood pressure." },

        { t: "h", text: "Cerebrolysin" },
        { t: "card", name: "Cerebrolysin", grade: "A", route: "Into muscle, or IV in hospitals", often: "Daily", length: "10 to 20 days", wada: "Not banned", note: "Most tested here, and the testing did not go its way." },
        { t: "p", text: "What it is. Not a single peptide but a soup of small peptides and amino acids extracted from pig brain, made by one company in Austria and sold in glass ampules. Used in hospitals in dozens of countries, mostly in Eastern Europe and Asia, for stroke, brain injury and dementia." },
        { t: "p", text: "The evidence: A for approval, disputed for benefit. It's the most clinically tested peptide in this lesson, and the testing didn't go its way. A 2020 review of the stroke trials found no benefit on death and a possible increase in serious side effects. Dementia trials showed modest effects that didn't lead to Western approval. It's still prescribed where it's approved." },
        { t: "p", text: "How people commonly use it. In hospitals, 5 to 10 milliliters injected into muscle or dripped into a vein, daily for ten to twenty days. Research-market use copies the muscle-injection course. Ampules are kept refrigerated, never frozen, and used soon after opening." },
        { t: "p", text: "What people notice. Sharper thinking and better mood over a course, and sometimes agitation or trouble sleeping in the first days. As a course of large muscle injections, it's the most demanding peptide in this course to use." },
        { t: "p", text: "Side effects, and who stays away. Agitation, headache, dizziness, injection pain. Where it's approved, it's not given to people with epilepsy or severe kidney problems. It's made from animals, which matters to some people on its own." },
        { t: "warn", text: "None of these replaces treatment for anxiety, depression or memory problems, and two of them can interact with the medications used for those. Anyone already on psychiatric medication is exactly the person whose prescriber needs to know." },
      ],
    },
    {
      slug: "sexual-function",
      title: "Sex drive and function",
      minutes: 12,
      free: false,
      summary: "PT-141 and kisspeptin. How they work, the nausea problem, and timing.",
      body: [
        { t: "h", text: "PT-141 (bremelanotide)" },
        { t: "card", name: "PT-141 (bremelanotide)", grade: "A / B", route: "Under the skin, 45 minutes or more before", often: "As needed; max 8 a month on the label", length: "Single doses", wada: "Not banned", note: "Works on desire in the brain. Nausea is the price." },
        { t: "p", text: "What it is. A peptide that works on desire in the brain rather than on blood flow, which is what makes it different from Viagra. It was derived from the tanning peptide melanotan 2. It's FDA-approved as Vyleesi for low sex drive in premenopausal women, as a single injection under the skin before sex." },
        { t: "p", text: "The evidence: A for its approved use, B for men. The approval trials showed a modest but real increase in desire, with a lot of people dropping out from nausea. Earlier trials in men with erectile problems showed it worked but weren't taken to approval, partly over blood-pressure findings with an older nasal version." },
        { t: "p", text: "How people commonly use it. The approved dose is 1.75 milligrams under the skin at least 45 minutes before, no more than once in 24 hours and no more than eight times a month. Research-market use in men reports 0.5 to 2 milligrams on the same timing, with many finding a lower dose plenty and the full dose too nauseating." },
        { t: "p", text: "What people notice. More desire and, in men, better erections, starting one to several hours after the dose and sometimes lasting into the next day. Nausea is the defining experience: about 40% of trial participants had it. The community advice to take it on an empty stomach and start low exists because of that." },
        { t: "p", text: "Side effects. Nausea, flushing, headache, and a temporary rise in blood pressure with a slower heartbeat for a few hours after each dose. Darkening of skin, gums and freckles with repeated use, which is its tanning-peptide heritage showing. Unwanted erections in men." },
        { t: "p", text: "Interactions, and who stays away. Uncontrolled high blood pressure or heart disease, because of the pressure rise. It slows the stomach and can reduce absorption of pills taken around the same time. Anyone for whom skin darkening would be a problem." },

        { t: "h", text: "Kisspeptin" },
        { t: "card", name: "Kisspeptin", grade: "B", route: "Under the skin", often: "Rare; no established practice", length: "Single doses in research", wada: "Not banned", note: "Research tool. Repeated use works against you." },
        { t: "p", text: "What it is. A brain peptide at the very top of the chain that controls your sex hormones. It tells the brain to release the signal that eventually raises testosterone or estrogen. It's also involved in how the brain processes attraction and emotion." },
        { t: "p", text: "The evidence: B, all in research settings. Human studies have used single doses to trigger egg maturation in IVF and to study brain responses to romantic and sexual images. There's no approved use, and no trial of the repeated use people buy it for." },
        { t: "p", text: "How people commonly use it. Rarely, and inconsistently. Reported doses vary widely and there's no established practice, because there's no established purpose. The biology actually works against repeated use: the hormone system gets desensitized to constant kisspeptin signaling, which is how related drugs are used to shut hormones down rather than raise them. Occasional use is what the research supports, if anything does." },
        { t: "p", text: "Side effects. Flushing and injection-site reactions in trials, at single doses. Nothing is known about repeated use." },
        { t: "note", text: "For desire, PT-141 is the one with the evidence and the approval, and nausea is the price. Kisspeptin is interesting science and, for now, a research tool rather than something with a use." },
      ],
    },
    {
      slug: "immune",
      title: "Immune system and inflammation",
      minutes: 15,
      free: false,
      summary: "Thymosin alpha-1, LL-37, KPV, glutathione. One with a real medical record, three that are mostly mechanism stories.",
      body: [
        { t: "h", text: "Thymosin alpha-1" },
        { t: "card", name: "Thymosin alpha-1", grade: "A / B", route: "Under the skin", often: "Twice a week", length: "Weeks to months", wada: "Not banned", note: "Approved in 30+ countries. The cleanest safety record in the course." },
        { t: "p", text: "What it is. A 28 amino acid peptide originally found in the thymus, the gland that trains your immune cells. Made in a lab and sold as a drug called thymalfasin or Zadaxin. It helps immune cells mature and work better. Approved in more than thirty countries, mainly for hepatitis B and C and to boost vaccine response, and studied widely in cancer and severe infections." },
        { t: "p", text: "The evidence: A for its approved uses, B for general immune support. Decades of clinical use with a nearly clean safety record. The trials for the popular use, getting sick less often if you're otherwise healthy, aren't there. What exists is a very good safety profile and people extrapolating from it." },
        { t: "p", text: "How people commonly use it. The medical dose is 1.6 milligrams under the skin twice a week, for months in the approved conditions. Research-market use copies that, or runs it at the same dose in shorter courses of a few weeks during or after an illness, or through a heavy training block." },
        { t: "p", text: "What people notice. Fewer or shorter colds over a season, which is hard to measure in one person. Some report feeling better during a course. Side effects are rare and minor: injection-site reactions, occasional mild aches." },
        { t: "p", text: "Interactions, and who stays away. Transplant patients on immune-suppressing drugs, because this peptide's job is to boost immune activity. Autoimmune conditions, for the same reason, though that's theoretical rather than documented. Otherwise the least troublesome peptide in this course." },

        { t: "h", text: "LL-37" },
        { t: "card", name: "LL-37", grade: "C", route: "Under the skin", often: "Daily", length: "Short courses", wada: "Not banned", note: "Your own antimicrobial peptide. Injection sites hurt." },
        { t: "p", text: "What it is. Your body's own antimicrobial peptide, made by immune cells and skin. It kills bacteria directly, breaks up the slimy layers bacteria hide in (biofilms), and signals the immune system. It's also involved in driving inflammation in psoriasis and rosacea, which is the flip side of the same activity." },
        { t: "p", text: "The evidence: C. Plenty of lab and animal work. Human data is limited to studies of it applied to wounds. Injecting it in healthy people has no trials." },
        { t: "p", text: "How people commonly use it. Reported at 50 to 100 micrograms under the skin daily, or near a suspected infection, in short courses. It's a niche peptide whose users are usually chasing a stubborn infection on the strength of the mechanism." },
        { t: "p", text: "Side effects. Injection-site pain and inflammation are common and sometimes severe, which fits a peptide whose purpose is to provoke the immune system. Anyone with psoriasis, rosacea or another inflammatory skin condition is the most likely to flare." },

        { t: "h", text: "KPV" },
        { t: "card", name: "KPV", grade: "C", route: "Swallowed, or under the skin", often: "Daily", length: "A few weeks", wada: "Not banned", note: "Tiny anti-inflammatory piece of a natural hormone. Cheap and mild." },
        { t: "p", text: "What it is. The last three building blocks of a natural anti-inflammatory hormone. KPV seems to keep the calming effect without the tanning effect, by turning down a central inflammation switch. It's small and tough enough to be swallowed." },
        { t: "p", text: "The evidence: C. Animal studies of gut inflammation, including versions that improved colitis in mice, and lab studies of skin inflammation. No human trials." },
        { t: "p", text: "How people commonly use it. Swallowed, 250 to 500 micrograms daily for gut complaints, which is where its reputation is, or under the skin at similar doses for general inflammation. Courses of a few weeks. It's one of the four peptides in the Klow blend." },
        { t: "p", text: "What people notice, and side effects. Less gut trouble in some, nothing in many. Reported side effects are minimal, which fits a tiny peptide your body already makes as part of a bigger hormone." },

        { t: "h", text: "Glutathione" },
        { t: "card", name: "Glutathione", grade: "B / C", route: "IV drip, or injection", often: "A few times a week", length: "Ongoing", wada: "Not banned", note: "Your main antioxidant. The NAC pill does the same job for less." },
        { t: "p", text: "What it is. Not really a peptide in the sense of the rest of this course, but a three-piece molecule every cell makes as its main antioxidant. Sold for injection and IV drips." },
        { t: "p", text: "The evidence: B for the pills your body turns into it, C for injecting it. Swallowed glutathione is poorly absorbed. N-acetylcysteine (NAC), which the body turns into glutathione, has real trials in several conditions. Injected and IV glutathione has clinic marketing, some small studies, and a long-running controversy over skin-lightening use that has drawn regulatory warnings in several countries." },
        { t: "p", text: "How people commonly use it. IV drips of 600 to 1,200 milligrams in clinics, and injections of a few hundred milligrams under the skin or into muscle in the research market, a few times a week." },
        { t: "p", text: "Side effects, and who stays away. Generally well tolerated. A sulfur smell after a dose. Rare breathing trouble with IV use in people with asthma, which is the one interaction worth knowing. And anyone for whom the cheap NAC pill would do the same job." },
        { t: "note", text: "Thymosin alpha-1 is the one peptide in this lesson with a real medical record. The others are mechanism stories, and KPV is the cheapest and least likely to cause trouble of the three." },
      ],
    },
    {
      slug: "tanning",
      title: "Melanotan 1 and 2",
      minutes: 10,
      free: false,
      summary: "The tanning peptides: what they do, the mole problem, and why this is the compound most people are warned off.",
      body: [
        { t: "h", text: "Melanotan 1 (afamelanotide)" },
        { t: "card", name: "Melanotan 1 (afamelanotide)", grade: "A / C", route: "Under the skin", often: "Daily, then a few times a week", length: "1 to 2 weeks, then maintenance", wada: "Not banned", note: "Approved as an implant for one rare condition. Tanning use has no trials." },
        { t: "p", text: "What it is. A lab copy of the hormone that tells skin cells to make pigment. Approved in Europe and the US, as Scenesse, as a slow-release implant for a rare genetic condition that makes sunlight painful. The approval is for that condition, at that dose, in that form." },
        { t: "p", text: "The evidence: A for its approved use, C for cosmetic tanning. The approval trials showed people with the condition could spend more pain-free time in sunlight. Nobody has trialled the injected powder for getting a tan." },
        { t: "p", text: "How people commonly use it. Reported at 0.5 to 1 milligram under the skin daily for a week or two, then a few times a week, with sun or a tanning bed to develop the tan. People choose it over melanotan 2 when they want the tan without the other effects." },

        { t: "h", text: "Melanotan 2" },
        { t: "card", name: "Melanotan 2", grade: "C", route: "Under the skin", often: "Daily, then a couple of times a week", length: "1 to 2 weeks, then maintenance", wada: "Not banned", note: "Regulator warnings in several countries. New and changing moles." },
        { t: "p", text: "What it is. A shorter version that hits several pigment-related switches at once rather than one. That's why it tans, kills appetite and raises sex drive all together, and why PT-141 was developed from it. Not approved anywhere, and the subject of formal warnings from health regulators in the UK, Australia and elsewhere." },
        { t: "p", text: "The evidence: C, with a documented harm signal. Small older trials showed tanning and the sexual effects. What has piled up since is case reports: new and changing moles, melanoma diagnosed after use, and pigment changes that didn't go away. Whether it causes melanoma or just brings existing spots to attention isn't resolved, and no trial will resolve it, because none will be run." },
        { t: "p", text: "How people commonly use it. A loading phase of 0.25 to 0.5 milligrams under the skin daily, rising toward 1 milligram, for one to two weeks alongside UV exposure, then a maintenance dose a couple of times a week. People start low because the first doses cause the worst nausea." },
        { t: "p", text: "What people notice. A tan that develops with far less sun than usual, appetite suppression that some use on purpose, and more sex drive along with unwanted erections in men. Also nausea, flushing and yawning after each dose, especially early on." },
        { t: "h", text: "Side effects across both" },
        { t: "list", items: [
          "Nausea, flushing and a red face after dosing, worse with melanotan 2.",
          "New moles, and existing moles getting darker, bigger, or changing shape. This is the finding behind the regulator warnings, and the reason a skin check before and during use is the universal advice.",
          "Uneven pigment: darkened freckles, patches, and darkening of the gums and genitals, some of it permanent.",
          "Loss of appetite and, with melanotan 2, unwanted erections and increased sex drive.",
          "Blood pressure changes, and a scattering of rarer reported problems in melanotan 2 users ranging from kidney injury to prolonged erections.",
        ] },
        { t: "h", text: "Who stays away" },
        { t: "p", text: "Anyone with a personal or family history of melanoma, a lot of moles, or fair skin that burns, which describes most of the people who want it. Pregnancy. Anyone unwilling to have their skin checked by someone who knows what a changing mole looks like. Of every peptide in this course, melanotan 2 is the one where the reported harm is most concrete and the benefit is most cosmetic. That's the honest framing." },
        { t: "warn", text: "A tan from these peptides is not sun protection. The pigment is real. The DNA repair that normally comes with a natural tan isn't guaranteed. People burn under them, and people have developed melanoma while using them. Sunscreen doesn't become optional." },
      ],
    },
  ],
};
