/**
 * Module 3: the compounds, by goal.
 *
 * Every compound follows one template so they can be compared: what it is,
 * what the evidence actually shows (graded A to D, see the first lesson), how
 * it is commonly used, what people report, side effects, interactions, and who
 * tends to avoid it. "Commonly used" describes reported practice from trials
 * and the community. It is not a recommendation for anyone, and the lessons say
 * so. Doses that are approved drug doses are labelled as such.
 */

export const MODULE_3 = {
  n: 3,
  slug: "the-compounds",
  title: "The compounds, by goal",
  summary: "Every compound on the reference site, written to one template: mechanism, evidence, how it is commonly used, what people report, side effects, interactions, who avoids it.",
  status: "ready",
  lessons: [
    {
      slug: "how-to-read-these-pages",
      title: "How to read these pages",
      minutes: 5,
      free: true,
      summary: "The template, what 'commonly used' means, and how evidence strength is graded throughout.",
      body: [
        { t: "p", text: "Every compound in this module is written to the same seven headings, so that a compound with forty years of clinical use and one with three rat studies are described in the same shape and the difference is obvious rather than hidden in the prose." },
        { t: "h", text: "The seven headings" },
        { t: "list", items: [
          "What it is. The molecule, where it came from, and what it does in the body in one plain paragraph.",
          "The evidence, graded. See below.",
          "How it is commonly used. Reported practice: the doses, routes, frequencies and durations that appear in trials where they exist and in community use where they do not. Approved drug doses are marked as approved. Nothing under this heading is a recommendation for you.",
          "What people report. The subjective experience, including the common experience of nothing.",
          "Side effects. The common ones, the rare ones, and the ones that mean stop.",
          "Interactions. Medications and conditions where the overlap is real.",
          "Who tends to avoid it. Not a medical judgment. The groups for whom the reported downside is worst.",
        ] },
        { t: "h", text: "The evidence grades" },
        { t: "list", items: [
          "A. Approved for a human use somewhere with large controlled trials behind it. What it does at the approved dose is established. What it does at other doses, in other people, for other reasons, is not.",
          "B. Human trials exist, controlled or not, but no approval for the use people want it for. Something is known about safety in people. Efficacy claims usually outrun the data.",
          "C. Animal and cell studies only. Everything about human use is inference. This is most of the market.",
          "D. Anecdote and vendor copy. Nothing here should be called evidence.",
        ] },
        { t: "note", text: "A grade describes the evidence for the popular use, not the compound. Semaglutide is grade A for weight loss and grade C for the anti-aging claims some people make about it. Where a compound has several uses at different grades, the lesson says which." },
        { t: "warn", text: "Reported dose ranges are reported, not endorsed. They are here because leaving them out would send you to a forum to find them, which is worse. Several of these compounds affect hormones, blood sugar or blood pressure. Module five is where the safety material lives, and it applies to everything here." },
      ],
    },
    {
      slug: "recovery-and-repair",
      title: "Recovery and repair",
      minutes: 25,
      free: false,
      summary: "BPC-157, TB-500 and the Wolverine blend. The animal evidence, the human gap, and how they are used together.",
      body: [
        { t: "p", text: "These are the most-bought compounds in the research market and the ones with the widest gap between how confidently they are discussed and how much is actually known. The animal data is genuinely striking. The human data is close to nonexistent. Both things are true, and this lesson holds both." },

        { t: "h", text: "BPC-157" },
        { t: "p", text: "What it is. A fifteen amino acid fragment of a protein found in human gastric juice, made synthetically. In animals it appears to act on blood vessel growth, nitric oxide signalling and growth factor pathways, which is why it shows up in studies of tendon, muscle, gut and nerve injury. It is stable in stomach acid, which is unusual for a peptide and is why oral use exists." },
        { t: "p", text: "Evidence: C for injury and gut, with a footnote. Hundreds of rodent studies, most from one research group in Croatia, show accelerated healing of tendon, ligament, muscle and gut lesions. A pharmaceutical version reached early human trials for inflammatory bowel disease over a decade ago and was never taken further. There are no published controlled human trials for injury. In 2023 the FDA placed it in a category that bars compounding pharmacies from making it, citing safety concerns about unknowns rather than known harms." },
        { t: "p", text: "How it is commonly used. Reported subcutaneous doses cluster around 200 to 500 micrograms once or twice daily, for four to eight weeks, often injected near the injury on the belief that it acts locally as well as systemically. For gut complaints, oral capsules and sublingual use are reported at similar milligram-per-day totals. Some people run it continuously; most cycle it with the injury." },
        { t: "p", text: "What people report. Faster resolution of tendon and soft-tissue pain is the most common report, usually within two to four weeks. Gut symptom relief is the second. A meaningful fraction report nothing, which given the dosing uncertainty and the placebo effect around pain is worth taking seriously." },
        { t: "p", text: "Side effects. Reported as mild and uncommon: nausea, dizziness, headache, injection-site irritation. The theoretical concern is that a compound which promotes blood vessel growth could feed a tumour that already exists. No human case has established this, and no human trial has ruled it out." },
        { t: "p", text: "Interactions. Nothing well documented. Because it affects nitric oxide signalling, people on nitrates or blood-pressure medication sometimes notice light-headedness. It is on the WADA prohibited list, which matters to anyone who competes in a tested sport." },
        { t: "p", text: "Who tends to avoid it. Anyone with a current or recent cancer, for the angiogenesis reason. Pregnant women. Tested athletes." },

        { t: "h", text: "TB-500" },
        { t: "p", text: "What it is. A short fragment of thymosin beta-4, a protein present in almost every human cell that regulates actin, the scaffolding protein cells use to move. Much of what is sold as TB-500 is the full thymosin beta-4 molecule rather than the fragment, and vendors rarely say which. Its proposed action is helping repair cells migrate to damaged tissue and reducing inflammation there." },
        { t: "p", text: "Evidence: C for injury, B for two narrow uses. Animal work on heart, skin and eye injury is extensive and includes a much-cited 2004 study on cardiac cell migration in mice. Thymosin beta-4 itself has been through human trials for dry eye and for chronic wounds, with mixed results. For the muscle and tendon uses it is bought for, there is no controlled human data." },
        { t: "p", text: "How it is commonly used. Reported as a loading phase of roughly 2 to 2.5 milligrams twice a week for four to six weeks, followed by a maintenance dose of similar size once or twice a month. It is dosed less often than BPC-157 because it is believed to persist in tissue well beyond its short blood half-life. Injection is usually subcutaneous and not necessarily near the injury." },
        { t: "p", text: "What people report. Improved flexibility and reduced stiffness are reported more often than outright healing. Some describe a brief head rush or lethargy after a dose. As with BPC-157, a substantial number report nothing they can attribute to it." },
        { t: "p", text: "Side effects. Head rush, transient fatigue, injection-site reactions. The same theoretical concern about promoting growth in tissue that should not be growing." },
        { t: "p", text: "Interactions. Nothing documented in humans. WADA prohibited." },
        { t: "p", text: "Who tends to avoid it. Current or recent cancer. Tested athletes. Anyone unwilling to accept a compound whose vendors do not always say which molecule is in the vial." },

        { t: "h", text: "The Wolverine blend" },
        { t: "p", text: "What it is. BPC-157 and TB-500 in one vial, usually in equal or near-equal milligram amounts. The logic is complementary mechanisms: one compound acting on vessel growth and local signalling, the other on cell migration. There is no study of the combination. Its popularity is a market phenomenon." },
        { t: "p", text: "How it is commonly used. Reported as daily or every-other-day subcutaneous doses that deliver a few hundred micrograms of BPC-157 alongside a few hundred micrograms to a milligram of TB-500, for four to eight weeks. Because the two components have different reported schedules when used alone, a blend forces a compromise on one of them." },
        { t: "p", text: "The trade-off worth understanding. A blend is convenient and it breaks the one-variable rule from module four. If the combination helps, you do not know which half did it. If it causes a side effect, you do not know which half to stop. People who want to learn what works for them tend to run the components separately first, then blend once they know." },
        { t: "warn", text: "Everything in this lesson sits on animal evidence for the uses people buy it for. That is not a reason to dismiss it and it is not a reason to treat forum confidence as data. Anyone with an injury that is not improving needs an actual diagnosis before any of this is relevant." },
      ],
    },
    {
      slug: "growth-hormone-axis",
      title: "The growth hormone axis",
      minutes: 30,
      free: false,
      summary: "CJC-1295 with and without DAC, ipamorelin, sermorelin, tesamorelin. Pulses versus bleed, timing, and the blood-sugar question.",
      body: [
        { t: "p", text: "Everything in this lesson works by asking the pituitary to release more of its own growth hormone rather than supplying the hormone directly. That is the whole point of the category, and the reason people choose it over synthetic growth hormone: the body's own feedback loops stay in place. Two mechanisms are involved, and most of the practice in this space is about combining them." },
        { t: "h", text: "The two levers" },
        { t: "list", items: [
          "GHRH analogues. Sermorelin, CJC-1295 in both forms, and tesamorelin all mimic growth hormone releasing hormone, the signal from the hypothalamus that tells the pituitary to release growth hormone. They raise the size of a pulse.",
          "Ghrelin mimetics, also called GHRPs or secretagogues. Ipamorelin is the one on this site. These act on a different receptor and trigger a pulse directly, while also suppressing somatostatin, the hormone that would otherwise dampen the release.",
          "Together they are synergistic: a GHRH analogue plus a ghrelin mimetic produces a larger pulse than either alone, which is why the CJC and ipamorelin blend exists.",
        ] },
        { t: "h", text: "Pulses versus bleed" },
        { t: "p", text: "Natural growth hormone release is pulsatile, with the largest pulse in the first hours of sleep. Short-acting compounds reproduce that: a dose before bed produces a pulse, then levels fall. CJC-1295 with DAC is the exception. It binds to albumin in the blood and keeps growth hormone elevated for a week per dose, which is convenient and also flattens the pulses into a continuous elevation people call a bleed. The pharmacology argument is that continuous elevation is further from physiology and more likely to produce the side effects listed below. Whether that matters at the doses used is not settled." },

        { t: "h", text: "Ipamorelin" },
        { t: "p", text: "What it is. A five amino acid ghrelin mimetic, developed in the 1990s. It is preferred over older compounds in its class because it triggers growth hormone release without meaningfully raising cortisol or prolactin, which the older GHRPs did." },
        { t: "p", text: "Evidence: B. Human pharmacology studies show it reliably produces a growth hormone pulse. It was developed toward a post-surgical use that was never approved. There are no controlled trials for the body composition, sleep or recovery uses people buy it for." },
        { t: "p", text: "How it is commonly used. Reported subcutaneous doses of 100 to 300 micrograms, one to three times a day, with a dose before bed being the constant. Taken on an empty stomach because food, especially carbohydrate and fat, blunts the pulse. Commonly run for eight to twelve weeks, then paused." },
        { t: "p", text: "What people report. Deeper sleep and vivid dreams, usually within the first week, are the most consistent report. Improved recovery and a slow shift in body composition over months are the next. Hunger after a dose is reported but far less than with older secretagogues." },

        { t: "h", text: "CJC-1295 without DAC" },
        { t: "p", text: "What it is. A modified form of the first 29 amino acids of GHRH, altered to survive longer in the blood than sermorelin. Also sold as Mod GRF 1-29. Half-life of about half an hour." },
        { t: "p", text: "Evidence: B. Human pharmacology data exists from the compound's development. No trials for the uses it is bought for." },
        { t: "p", text: "How it is commonly used. Almost always with ipamorelin, at roughly 100 micrograms of each per dose, one to three times daily on the same empty-stomach, before-bed pattern. On its own it is dosed similarly and used less often." },

        { t: "h", text: "CJC-1295 with DAC" },
        { t: "p", text: "What it is. The same molecule with a drug affinity complex attached, so it binds albumin and lasts about eight days." },
        { t: "p", text: "Evidence: B. A 2006 human study established prolonged growth hormone and IGF-1 elevation for a week or more after a single dose." },
        { t: "p", text: "How it is commonly used. Reported at 1 to 2 milligrams once a week. Chosen for convenience. Avoided by people who care about pulsatility, for the reason above." },

        { t: "h", text: "Sermorelin" },
        { t: "p", text: "What it is. GHRH 1-29 in its unmodified form. The oldest compound in the group, approved in the United States in 1997 as a diagnostic and treatment for growth hormone deficiency in children and later withdrawn for commercial rather than safety reasons. Still available through compounding pharmacies by prescription, which makes it the one compound here with a legitimate non-research route." },
        { t: "p", text: "Evidence: A for growth hormone deficiency, B for age-related decline. Decades of clinical use. Trials in older adults show modest increases in lean mass and some sleep changes, at a cost of the side effects below." },
        { t: "p", text: "How it is commonly used. The prescribing pattern from compounding clinics is 200 to 500 micrograms subcutaneously at bedtime, for several months. Research-market use copies it. Its half-life of ten to twenty minutes is why it is the weakest option per dose." },

        { t: "h", text: "Tesamorelin" },
        { t: "p", text: "What it is. A stabilised GHRH analogue, and the only compound in this lesson with a current FDA approval, for reducing abdominal fat in people with HIV-associated lipodystrophy. That approval means a full safety package exists." },
        { t: "p", text: "Evidence: A for visceral fat in its approved population, B for visceral fat and liver fat in others, and B for the cognitive findings in older adults that get cited. The approved dose is 2 milligrams subcutaneously once a day. Trials in people without HIV have shown reductions in liver fat." },
        { t: "p", text: "How it is commonly used. The approved dose, or 1 to 2 milligrams daily, usually at night. It is the most expensive compound in the group by a wide margin, which is why the tesamorelin and ipamorelin blend exists as a premium option rather than a default." },

        { t: "h", text: "Side effects across the group" },
        { t: "list", items: [
          "Water retention, and with it tingling or numbness in the hands that resembles carpal tunnel. The most common complaint, dose-related, and the first sign people are taking more than they need.",
          "Blood sugar. Growth hormone opposes insulin. Fasting glucose can rise, and people with prediabetes or diabetes notice it first. This is the interaction that matters most.",
          "Headache, flushing and injection-site reactions in the first days, usually fading.",
          "Hunger, particularly with ghrelin mimetics, ipamorelin least among them.",
          "Joint aches with sustained elevation, more reported with the DAC version.",
        ] },
        { t: "h", text: "Interactions and who tends to avoid it" },
        { t: "list", items: [
          "Diabetes and insulin resistance, for the blood sugar reason. Anyone on insulin or sulfonylureas is in territory that needs a clinician.",
          "Active cancer, because growth hormone and IGF-1 are growth signals, and this is the one group where the theoretical concern is taken seriously by everyone.",
          "Thyroid conditions: growth hormone changes thyroid hormone conversion and can unmask a low thyroid.",
          "Pregnancy. And anyone under about 25, whose own axis is still doing this on its own.",
          "Bloodwork people run: IGF-1 as the marker of effect, fasting glucose or HbA1c as the marker of cost. Module five covers timing.",
        ] },
        { t: "note", text: "The practical summary most experienced users arrive at: a short-acting GHRH analogue plus ipamorelin, before bed, on an empty stomach, in eight to twelve week blocks, with IGF-1 and fasting glucose checked. Everything else in this lesson is a variation on that." },
      ],
    },
    {
      slug: "metabolic",
      title: "Metabolic and weight",
      minutes: 30,
      free: false,
      summary: "Semaglutide, tirzepatide, retatrutide, AOD-9604. Titration as practised, the muscle-loss conversation, and what changed when compounding was restricted.",
      body: [
        { t: "p", text: "This is the one category where the compounds are, or are about to be, mainstream medicine. Two of the four are FDA-approved drugs with the largest weight-loss trials ever run behind them. That changes what the research-market version is: the same molecule, without the manufacturing oversight, the prescriber, or the titration schedule that the trials used to keep people safe. This lesson is mostly about that schedule." },

        { t: "h", text: "Semaglutide" },
        { t: "p", text: "What it is. A GLP-1 receptor agonist: a modified version of a gut hormone that slows stomach emptying, reduces appetite in the brain, and improves insulin release. Sold as Ozempic for diabetes and Wegovy for weight, once-weekly injection with a half-life of about a week." },
        { t: "p", text: "Evidence: A. The STEP trials showed roughly 15% body weight loss over 68 weeks at the 2.4 milligram dose against about 2.5% for placebo, plus cardiovascular benefit in a separate large trial. This is as good as evidence gets in this course." },
        { t: "p", text: "How it is commonly used. The approved schedule starts at 0.25 milligrams once a week for four weeks, then 0.5, then 1, then 1.7, then 2.4, each step held for at least four weeks. The schedule exists because the gastrointestinal side effects are dose-related and tolerance builds slowly. Research-market use copies this schedule when it goes well and skips steps when it does not, and skipping steps is where most of the vomiting comes from." },

        { t: "h", text: "Tirzepatide" },
        { t: "p", text: "What it is. A dual agonist, acting on the GLP-1 receptor and the GIP receptor, another gut hormone pathway. Sold as Mounjaro and Zepbound. Weekly injection, half-life around five days." },
        { t: "p", text: "Evidence: A. The SURMOUNT-1 trial showed around 21% body weight loss at the highest dose over 72 weeks, and a head-to-head trial published in 2024 found it beat semaglutide directly." },
        { t: "p", text: "How it is commonly used. The approved schedule starts at 2.5 milligrams weekly for four weeks, then rises in 2.5 milligram steps to a maximum of 15, each held four weeks or longer. The same rule applies: the schedule is the safety mechanism." },

        { t: "h", text: "Retatrutide" },
        { t: "p", text: "What it is. A triple agonist, adding the glucagon receptor to the other two, which is thought to increase energy expenditure and clear liver fat. Not approved anywhere. In late-stage trials." },
        { t: "p", text: "Evidence: B, heading toward A. A 2023 phase 2 trial showed about 24% weight loss at 48 weeks at the highest dose, the largest figure reported for any drug, and the larger phase 3 programme is under way. Long-term safety is not yet characterised, which is what phase 3 is for." },
        { t: "p", text: "How it is commonly used. There is no approved dose, and that is the point. Research-market use reports weekly doses starting around 1 to 2 milligrams and rising toward the trial's 8 to 12 milligram range over months. Everyone using it outside a trial is doing the phase 3 trial's job without the monitoring. Heart rate increases were notable in phase 2, and are the thing to watch." },

        { t: "h", text: "AOD-9604" },
        { t: "p", text: "What it is. A fragment of growth hormone, amino acids 176 to 191, intended to keep the fat-metabolism signal without the growth and blood-sugar effects of the whole hormone." },
        { t: "p", text: "Evidence: C for weight loss, with a history worth knowing. The company that developed it ran human trials in the 2000s that failed to show meaningful weight loss, and abandoned the drug. It later received a food-ingredient safety designation in the United States, which vendors present as approval. It is not. It is a statement that eating small amounts is safe." },
        { t: "p", text: "How it is commonly used. Reported at 250 to 500 micrograms subcutaneously daily, often in the morning before exercise. The honest summary is that its human trials were the test, and it did not pass them." },

        { t: "h", text: "What people report, across the GLP-1 group" },
        { t: "p", text: "Loss of appetite within the first week or two, sometimes total. Food noise, the background preoccupation with eating, goes quiet, and many people describe that as the real effect. Weight loss follows at roughly a pound or two a week at maintenance doses. Reduced interest in alcohol is reported often enough to be studied. Fatigue in the early weeks is common." },
        { t: "h", text: "Side effects" },
        { t: "list", items: [
          "Nausea, vomiting, constipation or diarrhoea. Most people get some. Dose-related, worst in the days after a step up, and the reason the schedule exists.",
          "Muscle loss. Rapid weight loss takes lean mass with it, and trials found a meaningful fraction of weight lost was not fat. Resistance training and adequate protein are the standard response, and are the single most-discussed topic among long-term users.",
          "Gallbladder problems and, rarely, pancreatitis. Severe persistent abdominal pain is a stop-and-see-someone symptom.",
          "Slowed stomach emptying to the point of gastroparesis in some people, and a documented interaction with anaesthesia. Surgeons and anaesthetists now ask about these drugs.",
          "Thyroid C-cell tumours in rodents, which produced a boxed warning and a contraindication for people with a personal or family history of medullary thyroid cancer or MEN2.",
          "Rebound. Stopping returns appetite, and most trial participants regained most of the weight within a year. This is a long-term drug, and the cost of research-market supply over years is part of the decision.",
        ] },
        { t: "h", text: "Interactions and who tends to avoid it" },
        { t: "list", items: [
          "Insulin and sulfonylureas: hypoglycaemia risk, needs a prescriber managing both.",
          "Any oral medication that needs steady absorption. Slowed gastric emptying changes how pills are absorbed; thyroid medication and the contraceptive pill are the ones people notice.",
          "Personal or family history of medullary thyroid cancer or MEN2. Pregnancy, and planning it: these are stopped months before.",
          "History of pancreatitis or gallbladder disease. Eating disorders. Anyone already at a low body weight.",
        ] },
        { t: "h", text: "What changed in the market" },
        { t: "p", text: "Compounding pharmacies were allowed to make semaglutide and tirzepatide while the branded drugs were in shortage. The FDA declared the tirzepatide shortage over in late 2024 and semaglutide in early 2025, and compounding was curtailed. The people who had been buying from compounders did not stop wanting the drug, and a large share moved to the research-chemical market. That is the context for why these two compounds now dominate vendor sales, and for why module one's sourcing lesson matters most here: a GLP-1 vial is the most-counterfeited product in this market." },
        { t: "warn", text: "Of everything in this course, these are the compounds where doing it without a prescriber is hardest to defend, because a prescription route exists, the drugs are potent, and the side effects can be serious. This lesson explains them because people are using them either way. It does not make that a good idea." },
      ],
    },
    {
      slug: "longevity-and-mitochondria",
      title: "Longevity and mitochondria",
      minutes: 20,
      free: false,
      summary: "Epithalon, MOTS-c, NAD+, SS-31, pinealon. Where the evidence is strong, where it is thin, and why cycling is the norm.",
      body: [
        { t: "p", text: "This is the category with the biggest claims and, with one exception, the thinnest evidence. The exception is a compound that has now become an approved drug for a rare disease, which is worth understanding because it shows what the others would need to become to justify their reputations." },

        { t: "h", text: "SS-31, elamipretide" },
        { t: "p", text: "What it is. A four amino acid peptide that concentrates in the inner membrane of mitochondria and binds cardiolipin, stabilising the machinery that makes energy. Developed by a pharmaceutical company over two decades." },
        { t: "p", text: "Evidence: A for Barth syndrome, B for everything else. After years of trials in heart failure, eye disease and mitochondrial myopathy that mostly missed their primary endpoints, it reached approval in the United States in 2025 for Barth syndrome, a rare inherited mitochondrial disease. Trials in age-related conditions have shown signals without clear wins. For the general anti-aging or performance use, the evidence is that it is safe enough to have been given to thousands of trial participants and that its effects in healthy people are unproven." },
        { t: "p", text: "How it is commonly used. Reported at 5 to 10 milligrams subcutaneously daily, in blocks of four to eight weeks. Injection-site reactions are the dominant complaint in trials and in practice." },

        { t: "h", text: "MOTS-c" },
        { t: "p", text: "What it is. A sixteen amino acid peptide encoded in mitochondrial DNA, released during exercise, which appears to act on the AMPK pathway that governs metabolism. Called an exercise mimetic because of what it does in mice." },
        { t: "p", text: "Evidence: C, with a failed human attempt. A 2020 mouse study showed improved physical performance and metabolic protection. A pharmaceutical analogue was tested in people for fatty liver and obesity and did not meet its endpoints, and the company stopped. That leaves animal data for the use people buy it for." },
        { t: "p", text: "How it is commonly used. Reported at 5 to 10 milligrams subcutaneously two or three times a week for four to six weeks, often timed before training. People report improved endurance and reduced fatigue. Some report nothing. Side effects reported are minor and local." },

        { t: "h", text: "NAD+" },
        { t: "p", text: "What it is. Not a peptide. A coenzyme involved in energy metabolism and DNA repair, which declines with age. Sold as a powder for injection and given by infusion in clinics." },
        { t: "p", text: "Evidence: B for the precursors, C for injected NAD+. Oral precursors such as NR and NMN have been through small human trials with mixed and modest results. Injected NAD+ has almost no controlled human data; its popularity comes from clinic marketing." },
        { t: "p", text: "How it is commonly used. Subcutaneous doses of 50 to 100 milligrams reported daily or several times a week, and intravenous infusions of several hundred milligrams in clinics. Infused quickly it produces chest tightness, flushing, cramping and nausea, which is why clinics run it over hours. Subcutaneous injection is reported as painful. People report energy and clarity, which is also what people report from an afternoon in a clinic chair." },

        { t: "h", text: "Epithalon" },
        { t: "p", text: "What it is. A four amino acid synthetic version of a pineal gland extract, from a Russian research programme that produced a family of short peptides they call bioregulators. Proposed to activate telomerase and regulate melatonin." },
        { t: "p", text: "Evidence: C, with a caveat about where the human data is. Cell studies from 2003 showed telomerase activation in human cells. Russian trials in elderly people reported reduced mortality over years, but they are old, from one group, and not replicated elsewhere. Outside that programme there is essentially nothing." },
        { t: "p", text: "How it is commonly used. Reported at 5 to 10 milligrams subcutaneously daily for ten to twenty days, once or twice a year. The short course and long gap come from the original Russian protocols. Side effects reported are rare and minor. People report better sleep during a course and little else they can point to, which is what you would expect from a compound whose proposed effect is on a decades-long process." },

        { t: "h", text: "Pinealon" },
        { t: "p", text: "What it is. A three amino acid peptide from the same Russian programme, proposed to act on brain cells and the pineal gland." },
        { t: "p", text: "Evidence: C, and thin even by the standards of this lesson. Animal and cell studies from the originating group." },
        { t: "p", text: "How it is commonly used. Reported in the same short-course pattern as epithalon, often alongside it. Almost no side effects reported, and almost no effects reported either." },

        { t: "h", text: "Why cycling is the norm here" },
        { t: "p", text: "None of these compounds has a feedback loop to protect, the way the growth hormone axis does. Cycling in this category is inherited from the Russian protocols and from caution: with compounds whose long-term effects in humans are unknown, taking them for limited periods with long gaps is the conservative default. It is not a rule derived from evidence, because the evidence to derive it from does not exist." },
        { t: "note", text: "An honest ranking for someone choosing one: SS-31 has the most human safety data. NAD+ precursors taken orally are the cheapest and best studied of the NAD options. Everything else here is a bet on animal data, and the bet is small money for probably nothing rather than any documented harm." },
      ],
    },
    {
      slug: "skin-and-hair",
      title: "Skin, hair and cosmetic",
      minutes: 15,
      free: false,
      summary: "GHK-Cu and the Glow and Klow blends. Topical versus injected, and what the copper is doing.",
      body: [
        { t: "h", text: "GHK-Cu" },
        { t: "p", text: "What it is. A three amino acid peptide bound to a copper ion. Present in human plasma and declining sharply with age. In cell and animal studies it increases collagen and elastin production, supports wound healing, and alters the expression of a large number of genes involved in repair. The copper is part of the mechanism, not a decoration." },
        { t: "p", text: "Evidence: B for topical use, C for injected. The cosmetic literature includes small controlled human trials of GHK-Cu creams showing improved skin thickness, firmness and wrinkle depth, which is why it appears in skincare products. Injected use for systemic anti-aging or hair growth has no human trials." },
        { t: "p", text: "How it is commonly used. Topically, in creams and serums at concentrations of around 1 to 3 percent, daily, indefinitely. Injected, reported at 1 to 2 milligrams subcutaneously daily for four to six weeks, sometimes near the area of interest, and for hair often applied to the scalp as a solution rather than injected." },
        { t: "p", text: "What people report. Topically: smoother skin over months, consistent with the trials. Injected: the most consistent report is that it stings badly at the injection site, followed by improved skin and hair over weeks that is hard to separate from other changes." },
        { t: "p", text: "Side effects. Injection-site pain is near universal and is the reason many people move to topical. Transient drops in blood pressure and light-headedness are reported at higher injected doses. Copper is a metal the body regulates carefully; sustained high-dose injection is an unstudied load." },
        { t: "p", text: "Interactions and who tends to avoid it. Wilson's disease or any copper-handling disorder. Anyone on blood-pressure medication who notices dizziness. Otherwise little documented." },

        { t: "h", text: "The Glow blend" },
        { t: "p", text: "What it is. GHK-Cu with BPC-157 and TB-500 in one vial: the recovery pairing plus the collagen peptide. Marketed for skin and healing together." },
        { t: "p", text: "How it is commonly used. Reported as daily subcutaneous doses delivering a milligram or so of GHK-Cu alongside a few hundred micrograms of each recovery peptide, for four to six weeks. The same trade-off as every blend: three compounds, three sets of possible side effects, one vial, no way to tell which did what." },

        { t: "h", text: "The Klow blend" },
        { t: "p", text: "What it is. Glow plus KPV, the anti-inflammatory tripeptide covered in the immune lesson. Marketed as a four-way healing blend for skin, gut and inflammation." },
        { t: "p", text: "How it is commonly used. As Glow, with KPV in the low hundreds of micrograms alongside. Four compounds in one vial is the point at which most careful users stop and ask what they are actually trying to fix, because a blend this broad is a statement of not knowing." },
        { t: "note", text: "The cheapest version of everything in this lesson is a GHK-Cu cream, which has the only human trials in the category. Injection adds cost, pain and uncertainty, and removes the evidence." },
      ],
    },
    {
      slug: "cognition-and-mood",
      title: "Cognition and mood",
      minutes: 18,
      free: false,
      summary: "Selank, semax, cerebrolysin. The Russian clinical history, nasal versus injected, and what to expect.",
      body: [
        { t: "p", text: "All three compounds here are approved medicines somewhere other than the United States, which puts them in an unusual position: real human data exists, in languages and journals most English-speaking buyers never read, and the research market sells them with none of the context that data provides." },

        { t: "h", text: "Selank" },
        { t: "p", text: "What it is. A seven amino acid analogue of tuftsin, an immune peptide, developed in Russia as an anti-anxiety agent. Approved there as a nasal solution. Proposed to modulate GABA signalling and raise BDNF, a growth factor for neurons." },
        { t: "p", text: "Evidence: A in Russia for anxiety, effectively B elsewhere because the trials were not conducted or replicated outside that system. Russian controlled trials reported anxiety reduction comparable to a benzodiazepine without sedation or dependence. Western replication is absent." },
        { t: "p", text: "How it is commonly used. Nasally, as drops or spray, at 250 to 500 micrograms one to three times a day; the nasal route is how it was developed and prescribed. Subcutaneous injection is reported at similar doses. Effects are described as lasting well beyond the compound's short half-life, up to a day or more. Used as needed or in courses of a few weeks." },
        { t: "p", text: "What people report. A calm, clear feeling without drowsiness, usually within an hour. Some report improved focus. A fair number report nothing, and tolerance with continuous daily use is reported often enough to explain why courses are short." },
        { t: "p", text: "Side effects. Fatigue and low mood in some users, nasal irritation, and little else documented. Interactions are not well studied; combining it with sedatives or alcohol is the common-sense caution." },

        { t: "h", text: "Semax" },
        { t: "p", text: "What it is. A fragment of ACTH, amino acids 4 to 10 with a modification, developed in the same Russian programme. Approved there for stroke recovery and cognitive impairment. Proposed to raise BDNF and NGF and to act on attention and memory circuits." },
        { t: "p", text: "Evidence: A in Russia for stroke, B elsewhere. Russian trials in stroke patients and in cognitive complaints reported benefit. A 2014 genomics study found it alters the expression of a large number of genes in brain tissue, which is cited as mechanism and is really a statement that it does a lot of things at once. No Western trials." },
        { t: "p", text: "How it is commonly used. Nasally, 200 to 600 micrograms daily in the morning, in courses of ten days to a few weeks. Stronger acetylated and amidated variants are sold at lower doses. Injection is uncommon." },
        { t: "p", text: "What people report. Improved focus and drive within the hour, sometimes with irritability. Effects wear off within the day. Reports of hair shedding during extended use circulate widely and have no published basis, but recur often enough to note." },
        { t: "p", text: "Side effects. Irritability, agitation, headache, and a rise in blood pressure in some users, which is the interaction that matters for anyone with hypertension." },

        { t: "h", text: "Cerebrolysin" },
        { t: "p", text: "What it is. Not a single peptide but a mixture of small peptides and amino acids derived from pig brain, made by one Austrian manufacturer and sold in ampoules. Used in hospitals in dozens of countries, mostly in Eastern Europe and Asia, for stroke, brain injury and dementia." },
        { t: "p", text: "Evidence: A for approval, contested for benefit. It is the most clinically tested compound in this lesson, and the testing did not go its way. A 2020 Cochrane review of acute stroke trials found no benefit on death and a possible increase in serious adverse events. Dementia trials showed modest effects that did not lead to Western approval. It remains prescribed where it is approved." },
        { t: "p", text: "How it is commonly used. Clinically, 5 to 10 millilitres by intramuscular injection or diluted intravenous infusion, daily for ten to twenty days. Research-market use copies the intramuscular course. Ampoules are refrigerated, never frozen, and used soon after opening." },
        { t: "p", text: "What people report. Improved mental clarity and mood over a course, and sometimes agitation or insomnia in the first days. As a course of large-volume intramuscular injections, it is the most demanding compound in this course to use." },
        { t: "p", text: "Side effects and who tends to avoid it. Agitation, headache, dizziness, injection-site pain. Contraindicated in the approved markets for epilepsy and severe kidney impairment. It is an animal-derived product, which matters to some people on its own." },
        { t: "warn", text: "None of these replaces treatment for anxiety, depression or cognitive decline, and two of them can interact with medications used for those conditions. Anyone already on psychiatric medication is in the territory where a prescriber needs to know." },
      ],
    },
    {
      slug: "sexual-function",
      title: "Sexual function",
      minutes: 12,
      free: false,
      summary: "PT-141 and kisspeptin. Mechanism, the nausea problem, and timing.",
      body: [
        { t: "h", text: "PT-141, bremelanotide" },
        { t: "p", text: "What it is. A melanocortin receptor agonist derived from the tanning peptide melanotan 2, acting on receptors in the brain involved in arousal rather than on blood flow. Approved in the United States as Vyleesi for low sexual desire in premenopausal women, as a single subcutaneous injection before sexual activity." },
        { t: "p", text: "Evidence: A for its approved use, B for men. The approval trials showed a modest but real increase in desire against placebo, with a high dropout rate from nausea. Earlier trials in men with erectile dysfunction showed effect but were not taken to approval, partly over blood pressure findings with an earlier nasal formulation." },
        { t: "p", text: "How it is commonly used. The approved dose is 1.75 milligrams subcutaneously at least 45 minutes before activity, no more than one dose in 24 hours and no more than eight a month. Research-market use in men reports 0.5 to 2 milligrams on the same timing, with many people finding a lower dose sufficient and the full dose too nauseating." },
        { t: "p", text: "What people report. Increased desire and, in men, improved erections, beginning one to several hours after the dose and sometimes lasting into the next day. Nausea is the defining experience: about 40% of trial participants had it, and the community advice to take it on an empty stomach and start low exists because of that." },
        { t: "p", text: "Side effects. Nausea, flushing, headache, and a transient rise in blood pressure with a drop in heart rate for a few hours after each dose. Darkening of the skin, gums and freckles with repeated use, which is the melanocortin heritage showing. Spontaneous erections in men." },
        { t: "p", text: "Interactions and who tends to avoid it. Uncontrolled high blood pressure or cardiovascular disease, because of the pressure rise. It slows stomach emptying and can reduce absorption of oral medications taken around the same time; naltrexone is the documented case. Anyone for whom skin darkening would be a problem." },

        { t: "h", text: "Kisspeptin" },
        { t: "p", text: "What it is. A hypothalamic peptide that sits at the top of the reproductive hormone cascade, triggering the release of GnRH and so of LH, FSH and the sex hormones. Also implicated in sexual and emotional brain processing." },
        { t: "p", text: "Evidence: B, all in research settings. Human studies have used single doses to trigger egg maturation in IVF and to probe brain responses to sexual and emotional cues. There is no approved use, and no trial of the repeated use people buy it for." },
        { t: "p", text: "How it is commonly used. Rarely, and inconsistently. Reported subcutaneous doses vary widely and there is no established practice, because there is no established purpose. The physiology cuts against repeated use: the reproductive axis desensitises to continuous kisspeptin signalling, which is how the related GnRH analogues suppress hormones rather than raise them. Occasional use is what the research supports, if anything does." },
        { t: "p", text: "Side effects. Flushing and injection-site reactions in trials, at single doses. Nothing is known about repeated use." },
        { t: "note", text: "For desire, PT-141 is the compound with the evidence and the approval, and the nausea is the price. Kisspeptin is interesting physiology and, for now, a research tool rather than something with a use." },
      ],
    },
    {
      slug: "immune",
      title: "Immune and inflammation",
      minutes: 15,
      free: false,
      summary: "Thymosin alpha-1, LL-37, KPV, glutathione. Approved elsewhere, studied here, used cautiously.",
      body: [
        { t: "h", text: "Thymosin alpha-1" },
        { t: "p", text: "What it is. A 28 amino acid peptide originally isolated from the thymus, made synthetically and sold as a drug called thymalfasin or Zadaxin. It enhances T-cell function and the maturation of immune cells. Approved in more than thirty countries, mainly for hepatitis B and C and as a vaccine adjuvant, and studied widely in cancer and sepsis." },
        { t: "p", text: "Evidence: A for its approved uses, B for general immune support. Decades of clinical use with a safety record that is close to clean. The efficacy trials for the popular use, recovering from or resisting infection in otherwise healthy people, are not there; what exists is extrapolation from a good safety profile." },
        { t: "p", text: "How it is commonly used. The clinical dose is 1.6 milligrams subcutaneously twice a week, for months in the approved conditions. Research-market use copies that, or runs it at the same dose in shorter courses of a few weeks during or after illness." },
        { t: "p", text: "What people report. Fewer or shorter infections over a season, which is a hard thing to measure in one person. Some report feeling better during a course. Side effects are rare and minor: injection-site reactions, occasional low-grade aches." },
        { t: "p", text: "Interactions and who tends to avoid it. Immunosuppressed transplant recipients, because the drug's job is to enhance immune activity. Autoimmune conditions, for the same reason, though this is theoretical rather than documented. Otherwise the least problematic compound in this course." },

        { t: "h", text: "LL-37" },
        { t: "p", text: "What it is. The only human cathelicidin, an antimicrobial peptide produced by immune and skin cells. It kills bacteria directly, breaks up biofilms, and signals to the immune system. It is also implicated in driving inflammation in psoriasis and rosacea, which is the other side of the same activity." },
        { t: "p", text: "Evidence: C. Extensive cell and animal work. Human data is limited to topical wound studies. Injection in healthy people has no trials." },
        { t: "p", text: "How it is commonly used. Reported at 50 to 100 micrograms subcutaneously daily or near the site of a suspected infection, in short courses. It is a niche compound whose users are usually chasing a stubborn infection or biofilm on the strength of the mechanism." },
        { t: "p", text: "Side effects. Injection-site pain and inflammation are common and sometimes severe, which fits a peptide whose purpose is to provoke immune activity. Anyone with psoriasis, rosacea or another inflammatory skin condition is in the group most likely to have it flare." },

        { t: "h", text: "KPV" },
        { t: "p", text: "What it is. The last three amino acids of alpha-MSH, a hormone with anti-inflammatory activity. KPV appears to keep that activity without the pigmentation effects, acting by damping NF-kB, a central inflammation switch. Small and stable enough to be taken orally." },
        { t: "p", text: "Evidence: C. Animal studies of gut inflammation, including nanoparticle formulations that improved colitis in mice, and cell studies of skin inflammation. No human trials." },
        { t: "p", text: "How it is commonly used. Orally at 250 to 500 micrograms daily for gut complaints, which is where its reputation is, or subcutaneously at similar doses for general inflammation. Courses of a few weeks. It is a component of the Klow blend." },
        { t: "p", text: "What people report and side effects. Reduced gut symptoms in some, nothing in many. Side effects reported are minimal, which fits a small peptide that the body already makes as part of a larger hormone." },

        { t: "h", text: "Glutathione" },
        { t: "p", text: "What it is. Not a peptide in the sense of the rest of this course, but a tripeptide the body makes in every cell as its main antioxidant. Sold for injection and infusion." },
        { t: "p", text: "Evidence: B for the precursors, C for injection. Oral glutathione is poorly absorbed; N-acetylcysteine, which the body turns into glutathione, has real trials in several conditions. Injected and infused glutathione has clinic marketing, some small studies, and a long-standing controversy over skin-lightening use that has produced regulatory warnings in several countries." },
        { t: "p", text: "How it is commonly used. Intravenous infusions of 600 to 1,200 milligrams in clinics, and subcutaneous or intramuscular injection of a few hundred milligrams reported in the research market, a few times a week." },
        { t: "p", text: "Side effects and who tends to avoid it. Generally well tolerated. A sulphur smell after dosing. Rare bronchospasm with intravenous use in people with asthma, which is the one interaction worth knowing. Anyone for whom the cheap oral precursor would do the same job." },
        { t: "note", text: "Thymosin alpha-1 is the one compound in this lesson with a clinical record. The others are mechanism stories, and KPV is the cheapest and least likely to cause trouble of the three." },
      ],
    },
    {
      slug: "tanning",
      title: "Melanotan 1 and 2",
      minutes: 10,
      free: false,
      summary: "What they do, the mole question, and why this is the compound most people are warned off.",
      body: [
        { t: "h", text: "Melanotan 1, afamelanotide" },
        { t: "p", text: "What it is. A synthetic analogue of alpha-MSH, the hormone that tells skin cells to make melanin. Approved in Europe and the United States, as Scenesse, as a slow-release implant for a rare genetic condition that makes sunlight painful. The approval is for that condition, at that dose, in that form." },
        { t: "p", text: "Evidence: A for its approved use, C for cosmetic tanning. The approval trials showed increased pain-free sun exposure in people with the condition. Nobody has trialled the injected powder for tanning." },
        { t: "p", text: "How it is commonly used. Reported at 0.5 to 1 milligram subcutaneously daily for a week or two, then a few times a week, with sun or UV exposure to develop the tan. It is chosen over melanotan 2 by people who want the tan without the other effects." },

        { t: "h", text: "Melanotan 2" },
        { t: "p", text: "What it is. A shorter, cyclic analogue that hits several melanocortin receptors rather than one. That broadness is why it tans, suppresses appetite and increases libido at once, and why PT-141 was derived from it. Not approved anywhere, and the subject of formal warnings from regulators in the UK, Australia and elsewhere." },
        { t: "p", text: "Evidence: C, with a documented harm signal. Small older trials showed tanning and the sexual effects. What has accumulated since is case reports: new and changing moles, melanoma diagnosed after use, and pigmentation changes that did not reverse. Whether it causes melanoma or brings existing lesions to attention is unresolved, and no trial will resolve it, because none will be run." },
        { t: "p", text: "How it is commonly used. Reported as a loading phase of 0.25 to 0.5 milligrams subcutaneously daily, rising toward 1 milligram, for one to two weeks alongside UV exposure, then a maintenance dose a couple of times a week. Users start low because the first doses produce the worst nausea." },
        { t: "p", text: "What people report. A tan that develops with far less sun than usual, appetite suppression that some use deliberately, and increased libido and spontaneous erections. Also nausea, flushing and yawning after each dose, especially early." },
        { t: "h", text: "Side effects across both" },
        { t: "list", items: [
          "Nausea, flushing and facial redness after dosing, worse with melanotan 2.",
          "New moles, and existing moles darkening, growing or changing. This is the finding that produces the warnings, and the reason a skin check before and during use is the universal advice.",
          "Uneven pigmentation: darkened freckles, patches, and darkening of the gums and genitals, some of it lasting.",
          "Appetite loss and, with melanotan 2, spontaneous erections in men and increased libido in both sexes.",
          "Blood pressure changes, and a case literature of rarer events in melanotan 2 users that ranges from kidney injury to priapism.",
        ] },
        { t: "h", text: "Who tends to avoid it" },
        { t: "p", text: "Anyone with a personal or family history of melanoma, many moles, or fair skin that burns, which describes most of the people who want it. Pregnancy. Anyone unwilling to have their skin checked by someone who knows what a changing mole looks like. Of every compound in this course, melanotan 2 is the one where the reported harm is most concrete and the benefit is most cosmetic, and that is the honest framing." },
        { t: "warn", text: "A tan from these compounds is not sun protection. The melanin is real; the DNA repair that normally accompanies a tan is not guaranteed to be. People burn under them and people have developed melanoma while using them. Sunscreen does not become optional." },
      ],
    },
  ],
};
