// ============================================================
// Backend / partner endpoints
// ============================================================
export const CHAT_ENDPOINT = "https://peptide-proxy.richardtaylor829844.workers.dev";
export const EMAIL_ENDPOINT = "https://formspree.io/f/mrerlwak";

// Big ad (bottom / peptide detail / concern pages) — Uprise Consulting Group
export const AD_LINK = "https://uprisecg.com/";
export const AD_BRAND = "Uprise Consulting Group";
export const AD_LOGO = "https://uprisecg.com/wp-content/uploads/2025/03/Uprise-Consulting-Group-Inc-Logo-White.webp";
// Compact ad (top banner) — Vuori
export const COMPACT_AD_LINK = "https://vuoriclothing.com/";
export const COMPACT_AD_BRAND = "Vuori";

export const DISCLAIMER_VERSION = "2026-04-20";

export const S = {
  bg: "#0B1120", card: "#141D2F", surf: "#0E1528",
  a: "#5EEAD4", ab: "rgba(94,234,212,.08)", abr: "rgba(94,234,212,.15)",
  t: "#E2E8F0", d: "#94A3B8", m: "#64748B", br: "rgba(255,255,255,.06)",
  w: "#FCD34D", wb: "rgba(252,211,77,.08)", wbr: "rgba(252,211,77,.15)",
  f: "'Outfit',sans-serif"
};

export const CONCERNS = [
  {id:"recovery",label:"Injury & Recovery",icon:"🩹",sub:"Muscle, tendon, joint, or tissue healing",peps:["bpc157","tb500","ll37","wolverine"]},
  {id:"gut",label:"Gut Health",icon:"💚",sub:"Digestion, inflammation, leaky gut",peps:["bpc157","kpv","glutathione","klow"]},
  {id:"weight",label:"Weight Loss",icon:"⚡",sub:"Fat loss, appetite, metabolism",peps:["semaglutide","tirzepatide","retatrutide","aod9604"]},
  {id:"aging",label:"Anti-Aging",icon:"✨",sub:"Longevity, energy, cellular health",peps:["epithalon","ss31","nad","motsc","ghkcu"]},
  {id:"immune",label:"Immune Support",icon:"🛡️",sub:"Immunity, inflammation, defense",peps:["ta1","kpv","ll37","glutathione"]},
  {id:"brain",label:"Brain & Focus",icon:"🧠",sub:"Memory, mood, mental clarity",peps:["selank","semax","cerebrolysin","pinealon"]},
  {id:"skin",label:"Skin & Hair",icon:"💫",sub:"Collagen, glow, hair growth, tanning",peps:["ghkcu","mt1","mt2","glow"]},
  {id:"sleep",label:"Sleep & Growth Hormone",icon:"🌙",sub:"Better sleep, GH, recovery",peps:["cjcipa","ipamorelin","sermorelin","tesamorelin","tesamipa","cjcnodac"]},
  {id:"sexual",label:"Sexual Health",icon:"❤️",sub:"Libido, performance, hormones",peps:["pt141","kisspeptin","mt2"]}
];

export const PEPS = {
  bpc157:{name:"BPC-157",cat:"Recovery",mw:"1419.5 Da",best:"Injury recovery, gut issues",why:"One of the most popular recovery peptides. Researched for gut healing, tendon/ligament repair, and tissue recovery.",plain:"Think of it as your body's natural repair signal, amplified. Researchers have studied it for everything from gut lining repair to injured tendons.",areas:["Gut healing and protection","Tendon and ligament repair","Muscle recovery","Joint inflammation","Wound healing"],studies:[{t:"BPC 157 in inflammatory bowel disease trials",j:"Curr Pharm Des",y:2011}],seq:"15 amino acid chain from gastric juice",store:"Keep frozen as powder. Refrigerate once mixed."},
  tb500:{name:"TB-500",cat:"Recovery",mw:"4963 Da",best:"Tissue repair, inflammation",why:"A synthetic version of a protein your body already makes. Studied for helping cells migrate to injury sites.",plain:"Your body sends TB-4 to damaged areas naturally. TB-500 is the research version of that repair signal.",areas:["Cell migration to injuries","Heart tissue repair","Reducing inflammation","Hair regrowth","Wound healing"],studies:[{t:"Thymosin B4 promotes cardiac cell migration",j:"Nature",y:2004}],seq:"Active fragment of Thymosin Beta-4",store:"Keep frozen as powder. Refrigerate once mixed."},
  ll37:{name:"LL-37",cat:"Recovery",mw:"4493 Da",best:"Infections, wound healing",why:"Your body's own antimicrobial weapon. Fights bacteria, breaks up biofilms, helps wounds heal.",plain:"Your immune system's first line of defense — kills harmful bacteria and helps repair the damage they cause.",areas:["Fighting bacterial infections","Breaking up biofilms","Wound healing","Immune defense","Skin healing"],studies:[{t:"LL-37 the only human cathelicidin",j:"Biochim Biophys Acta",y:2006}],seq:"37 amino acid antimicrobial peptide",store:"Keep frozen as powder. Refrigerate once mixed."},
  kpv:{name:"KPV",cat:"Immune",mw:"342 Da",best:"Gut inflammation, immune balance",why:"A tiny 3-amino-acid peptide that calms inflammation by turning down NF-kB, one of the body's main inflammation switches.",plain:"If inflammation is a fire, KPV helps turn off the alarm system that keeps adding fuel. Especially studied for gut inflammation.",areas:["Calming gut inflammation","Reducing intestinal swelling","Skin inflammation","Immune system balance","Antimicrobial effects"],studies:[{t:"KPV nanoparticles reduce intestinal inflammation",j:"Biomaterials",y:2020}],seq:"3 amino acids: Lys-Pro-Val",store:"Keep frozen as powder. Refrigerate once mixed."},
  ta1:{name:"Thymosin Alpha-1",cat:"Immune",mw:"3108 Da",best:"Immune boost, fighting illness",why:"One of the most proven immune peptides. Approved as a medication in 35+ countries.",plain:"This is the real deal — approved in dozens of countries. It trains your immune system to work better.",areas:["Boosting T-cell function","Fighting viral infections","Immune system training","Vaccination response","Recovery from illness"],studies:[{t:"Thymosin alpha-1 comprehensive review",j:"Expert Opin Biol Ther",y:2010}],seq:"28 amino acids from the thymus gland",store:"Keep frozen as powder. Refrigerate once mixed."},
  glutathione:{name:"Glutathione",cat:"Immune",mw:"307 Da",best:"Detox, overall health",why:"Called the master antioxidant. Every cell uses it. Levels drop as you age.",plain:"Your body's #1 detox and defense molecule. If you're feeling run down or toxic, your glutathione is probably low.",areas:["Detoxification","Reducing oxidative stress","Liver protection","Immune cell fuel","Anti-aging"],studies:[{t:"Glutathione metabolism and health",j:"J Nutr",y:2004}],seq:"3 amino acids: Glu-Cys-Gly",store:"Keep frozen as powder. Refrigerate once mixed."},
  ghkcu:{name:"GHK-Cu",cat:"Longevity",mw:"404 Da",best:"Skin, hair, anti-aging",why:"A copper peptide your body makes less of as you age. May turn on 4,000+ repair genes.",plain:"Your skin made tons of this when you were young. By 60, you have almost none. Research shows it restarts collagen production and DNA repair.",areas:["Collagen production","Skin tightening and glow","Hair growth","Wound healing","Gene activation for repair"],studies:[{t:"GHK peptide modulates cellular pathways",j:"Biomed Res Int",y:2015}],seq:"3 amino acids + copper",store:"Keep frozen as powder. Refrigerate once mixed."},
  ss31:{name:"SS-31",cat:"Longevity",mw:"641 Da",best:"Energy, cellular aging",why:"Goes directly into your mitochondria and repairs them. One of few peptides in human clinical trials.",plain:"As you age, your cells' engines break down and you lose energy. SS-31 is like a mechanic that fixes each cell's engine from the inside.",areas:["Mitochondrial repair","Cellular energy","Heart function","Kidney protection","Exercise performance"],studies:[{t:"Elamipretide in Barth syndrome trial",j:"Genet Med",y:2021}],seq:"4 amino acids targeting mitochondria",store:"Keep frozen as powder. Refrigerate once mixed."},
  epithalon:{name:"Epithalon",cat:"Longevity",mw:"390 Da",best:"Aging, sleep, telomeres",why:"The only peptide shown to activate telomerase — the enzyme that protects your DNA caps from shortening.",plain:"Your DNA has protective caps that get shorter every time cells divide. Epithalon may help rebuild them.",areas:["Telomere protection","Sleep and melatonin regulation","Circadian rhythm reset","Anti-aging genes","Antioxidant defense"],studies:[{t:"Epithalon induces telomerase in human cells",j:"Bull Exp Biol Med",y:2003}],seq:"4 amino acids: Ala-Glu-Asp-Gly",store:"Keep frozen as powder. Refrigerate once mixed."},
  motsc:{name:"MOTS-c",cat:"Longevity",mw:"2175 Da",best:"Metabolism, fitness, aging",why:"Called exercise in a molecule. Your mitochondria make this naturally and it mimics working out.",plain:"Your body releases MOTS-c when you exercise. It helps burn fat and improve insulin sensitivity — even without the gym.",areas:["Exercise mimetic effects","Blood sugar regulation","Fat metabolism","Physical performance","Metabolic protection"],studies:[{t:"MOTS-c regulates physical decline",j:"Nat Commun",y:2020}],seq:"16 amino acids from mitochondrial DNA",store:"Keep frozen as powder. Refrigerate once mixed."},
  nad:{name:"NAD+",cat:"Longevity",mw:"663 Da",best:"Energy, aging, brain fog",why:"A coenzyme that drops 50% by middle age. Low NAD+ means low energy, poor DNA repair, faster aging.",plain:"NAD+ is fuel for your cells' repair machinery. When it drops with age, everything starts breaking down faster.",areas:["Cellular energy","DNA repair","Longevity gene activation","Brain function","Metabolism"],studies:[{t:"NAD+ repletion improves mitochondrial function",j:"Science",y:2016}],seq:"Coenzyme (not a peptide)",store:"Keep frozen as powder. Refrigerate once mixed."},
  pinealon:{name:"Pinealon",cat:"Cognitive",mw:"404 Da",best:"Brain health, neuroprotection",why:"A Russian-developed bioregulator for brain and nervous system support.",plain:"A tiny 3-amino-acid peptide studied for protecting brain cells and supporting cognitive function as you age.",areas:["Brain cell protection","Nervous system support","Cognitive aging","Pineal gland function","Neuroprotection"],studies:[{t:"Neuroprotective EDR peptide in Alzheimer's models",j:"Bull Exp Biol Med",y:2016}],seq:"3 amino acids: Glu-Asp-Arg",store:"Keep frozen as powder. Refrigerate once mixed."},
  cjcnodac:{name:"CJC-1295 No DAC",cat:"Growth Hormone",mw:"3368 Da",best:"GH optimization, sleep",why:"Tells your pituitary to release growth hormone in natural pulses — like when you were younger.",plain:"As you age, your GH pulses weaken. This peptide turns up the volume without flooding your system.",areas:["Natural GH pulse stimulation","Better sleep","Fat loss","Lean muscle","Recovery"],studies:[{t:"Modified GRF(1-29) in healthy subjects",j:"J Clin Endocrinol Metab",y:2006}],seq:"29 amino acid GHRH analog",store:"Keep frozen as powder. Refrigerate once mixed."},
  cjcdac:{name:"CJC-1295 with DAC",cat:"Growth Hormone",mw:"~3647 Da",best:"Sustained GH elevation",why:"Long-acting version. Keeps GH elevated for almost a week per dose.",plain:"Same idea but stays active 6-8 days instead of hours. Simpler dosing, less natural pulsing.",areas:["Sustained GH elevation","Once-weekly dosing","IGF-1 increase","Body composition"],studies:[{t:"Prolonged GH after CJC-1295-DAC",j:"J Clin Endocrinol Metab",y:2006}],seq:"GHRH analog + albumin-binding complex",store:"Keep frozen as powder. Refrigerate once mixed."},
  ipamorelin:{name:"Ipamorelin",cat:"Growth Hormone",mw:"712 Da",best:"Clean GH boost, sleep",why:"The cleanest GH booster. Unlike older ones, it doesn't spike cortisol or prolactin.",plain:"Most GH peptides have side effects. Ipamorelin is the exception — boosts GH cleanly without messing with stress hormones.",areas:["Clean GH release","No cortisol spike","Bone density","Lean muscle","Better sleep"],studies:[{t:"Ipamorelin induces GH release",j:"Growth Horm IGF Res",y:1998}],seq:"5 amino acid ghrelin mimetic",store:"Keep frozen as powder. Refrigerate once mixed."},
  sermorelin:{name:"Sermorelin",cat:"Growth Hormone",mw:"3358 Da",best:"GH decline, sleep quality",why:"The OG of GH peptides. Originally FDA-approved in 1997 (Geref), later withdrawn from US market for commercial reasons — still available via compounding pharmacies.",plain:"The GH peptide with the longest clinical history. Used for decades in research and hormone clinics. Less potent than newer options but the most data behind it.",areas:["Longest clinical history","Natural GH stimulation","Deep sleep","Age-related GH decline","Lean body mass"],studies:[{t:"Sermorelin for adult GH insufficiency",j:"Clin Interv Aging",y:2012}],seq:"First 29 amino acids of GHRH",store:"Keep frozen as powder. Refrigerate once mixed."},
  tesamorelin:{name:"Tesamorelin",cat:"Growth Hormone",mw:"5136 Da",best:"Belly fat, metabolic health",why:"The only GH peptide with full FDA approval for therapeutic use. Approved for reducing belly fat.",plain:"FDA-approved to shrink dangerous belly fat. Also studied for brain health and liver fat. The gold standard.",areas:["FDA-approved for belly fat","Visceral fat reduction","Liver fat (NAFLD)","Cognitive function","IGF-1 normalization"],studies:[{t:"Tesamorelin reduces liver fat",j:"Hepatology",y:2019}],seq:"44 amino acid stabilized GHRH",store:"Keep frozen as powder. Refrigerate once mixed."},
  selank:{name:"Selank",cat:"Cognitive",mw:"752 Da",best:"Anxiety, focus, mood",why:"Anti-anxiety peptide approved in Russia. Works like a benzo without sedation or addiction. Boosts BDNF.",plain:"Calms anxiety and sharpens your mind at the same time. Anti-anxiety without the drowsiness.",areas:["Anxiety relief without sedation","Brain growth factor (BDNF)","Memory improvement","Mood stabilization","Focus and clarity"],studies:[{t:"Selank enhances neurotrophic factors",j:"Bull Exp Biol Med",y:2006}],seq:"7 amino acid tuftsin analog",store:"Keep frozen as powder. Refrigerate once mixed."},
  semax:{name:"Semax",cat:"Cognitive",mw:"814 Da",best:"Focus, brain health",why:"Approved in Russia for stroke recovery. Boosts BDNF and NGF — your brain's fertilizer.",plain:"Helps your brain grow new connections and protect existing ones. Used for stroke patients and cognitive decline.",areas:["Brain growth factors","Stroke recovery","Focus and attention","Neuroprotection","Mood and motivation"],studies:[{t:"Semax affects 1,000+ genes",j:"BMC Genomics",y:2014}],seq:"7 amino acid ACTH fragment",store:"Keep frozen as powder. Refrigerate once mixed."},
  cerebrolysin:{name:"Cerebrolysin",cat:"Cognitive",mw:"Mixture",best:"Brain injury, cognitive decline",why:"A mix of brain growth factors used in hospitals in 50+ countries for stroke and brain injuries.",plain:"A cocktail of brain repair proteins. The most clinically tested brain peptide — used in real hospitals.",areas:["Stroke recovery","Alzheimer's research","Brain injury repair","Memory and learning","Brain cell growth"],studies:[{t:"Cerebrolysin for acute stroke",j:"Cochrane Database",y:2020}],seq:"Mixture of neuropeptides",store:"Refrigerate the ampule. Do not freeze. Use soon after opening."},
  aod9604:{name:"AOD-9604",cat:"Metabolic",mw:"1815 Da",best:"Fat loss, joint health",why:"The fat-burning part of growth hormone without the side effects. No blood sugar issues.",plain:"Scientists took just the fat-burning part of GH and made it its own peptide. Fat loss without the downsides.",areas:["Fat burning without GH sides","No IGF-1 increase","No blood sugar impact","Joint/cartilage support","FDA GRAS status"],studies:[{t:"AOD9604 stimulates lipolysis",j:"Int J Obes",y:2000}],seq:"Fragment of GH (aa 177-191)",store:"Keep frozen as powder. Refrigerate once mixed."},
  semaglutide:{name:"Semaglutide",cat:"Metabolic",mw:"4114 Da",best:"Significant weight loss",why:"The blockbuster (Ozempic/Wegovy). FDA-approved with trials showing 15-17% weight reduction.",plain:"The one everyone is talking about. FDA-approved, backed by the biggest weight loss trials ever.",areas:["FDA-approved weight loss","Appetite suppression","Blood sugar control","Heart health","Liver fat reduction"],studies:[{t:"STEP trials for obesity",j:"N Engl J Med",y:2021}],seq:"Modified GLP-1 with fatty acid",store:"Keep frozen as powder. Refrigerate once mixed."},
  tirzepatide:{name:"Tirzepatide",cat:"Metabolic",mw:"4814 Da",best:"Maximum weight loss",why:"Hits TWO receptors. Beats semaglutide in head-to-head trials (up to 22.5% weight loss).",plain:"If semaglutide is impressive, tirzepatide is the upgrade. Outperformed Ozempic in every trial.",areas:["Beats semaglutide","Dual hormone pathway","Up to 22.5% weight loss","Better blood sugar","FDA-approved"],studies:[{t:"Tirzepatide vs semaglutide",j:"N Engl J Med",y:2024}],seq:"Dual GIP/GLP-1 agonist",store:"Keep frozen as powder. Refrigerate once mixed."},
  retatrutide:{name:"Retatrutide",cat:"Metabolic",mw:"~4600 Da",best:"Cutting-edge weight loss",why:"THREE receptors. Phase 2 showed 24.2% weight reduction — more than anything before it.",plain:"Triple action: suppresses appetite, burns more energy, AND clears liver fat. Nothing else hits all three.",areas:["Triple receptor activation","24%+ weight loss","Increased energy burn","Liver fat clearance","Next-generation"],studies:[{t:"Retatrutide for obesity Phase 2",j:"N Engl J Med",y:2023}],seq:"Triple GIP/GLP-1/Glucagon agonist",store:"Keep frozen as powder. Refrigerate once mixed."},
  pt141:{name:"PT-141",cat:"Sexual Health",mw:"1025 Da",best:"Libido, sexual function",why:"FDA-approved (Vyleesi) for low sex drive. Works in the brain, not blood vessels — different from Viagra.",plain:"Viagra works on plumbing. PT-141 works on desire. Activates arousal centers in your brain. Works for both men and women.",areas:["Brain-based arousal","Works for men and women","FDA-approved for HSDD","Different from Viagra","Melanocortin pathway"],studies:[{t:"Bremelanotide for HSDD",j:"Obstet Gynecol",y:2019}],seq:"Cyclic 7 amino acid peptide",store:"Keep frozen as powder. Refrigerate once mixed."},
  kisspeptin:{name:"Kisspeptin",cat:"Sexual Health",mw:"5861 Da",best:"Hormones, fertility",why:"The master switch for reproductive hormones. Triggers the entire hormone cascade.",plain:"The ignition key for your reproductive system. Triggers GnRH which triggers everything downstream.",areas:["Hormone cascade activation","Fertility support","LH/FSH stimulation","IVF research","Reproductive health"],studies:[{t:"Kisspeptin triggers egg maturation in IVF",j:"J Clin Invest",y:2014}],seq:"Hypothalamic neuropeptide",store:"Keep frozen as powder. Refrigerate once mixed."},
  mt1:{name:"Melanotan 1",cat:"Skin",mw:"1647 Da",best:"Skin protection, tanning",why:"FDA-approved (Scenesse). Stimulates melanin for natural UV protection.",plain:"Tells your skin to produce more melanin. FDA-approved with real clinical safety data.",areas:["FDA-approved","Natural melanin production","UV protection","Skin pigmentation","DNA repair in skin"],studies:[{t:"Afamelanotide for EPP Phase III",j:"N Engl J Med",y:2015}],seq:"13 amino acid a-MSH analog",store:"Keep frozen as powder. Refrigerate once mixed."},
  mt2:{name:"Melanotan 2",cat:"Skin",mw:"1024 Da",best:"Tanning, multiple benefits",why:"Broader-acting: tanning + appetite suppression + libido boost.",plain:"Does several things: tanning, appetite reduction, and libido. Less targeted but more versatile than MT-1.",areas:["Tanning and pigmentation","Appetite suppression","Sexual function boost","Multiple receptor activation"],studies:[{t:"Melanotan II for tanning",j:"Br J Dermatol",y:2009}],seq:"Cyclic a-MSH analog",store:"Keep frozen as powder. Refrigerate once mixed."},
  wolverine:{name:"Wolverine Blend",cat:"Blends",mw:"BPC-157 + TB-500",best:"Injury recovery, healing",why:"The most popular recovery stack. BPC-157 heals + TB-500 sends repair cells to the injury.",plain:"Two best recovery peptides combined. BPC-157 heals from the inside while TB-500 sends repair cells to the injury.",areas:["Dual repair pathways","Faster tissue healing","Joint and tendon recovery","Reduced inflammation","Comprehensive recovery"],studies:[{t:"See individual BPC-157 and TB-500 data",j:"Multiple",y:2020}],seq:"BPC-157 + TB-500 combined",store:"Keep frozen as powder. Refrigerate once mixed."},
  glow:{name:"Glow Blend",cat:"Blends",mw:"GHK-Cu + BPC-157 + TB-500",best:"Skin, recovery, anti-aging",why:"Wolverine + GHK-Cu for collagen. Three peptides covering tissue repair, collagen, and gene activation.",plain:"Everything in Wolverine plus a copper peptide that rebuilds collagen and activates repair genes. The full package.",areas:["Collagen + tissue repair","Skin rejuvenation","Wound healing","Gene activation","Anti-aging + recovery"],studies:[{t:"See individual component data",j:"Multiple",y:2020}],seq:"GHK-Cu + BPC-157 + TB-500",store:"Keep frozen as powder. Refrigerate once mixed."},
  klow:{name:"Klow Blend",cat:"Blends",mw:"4 peptides combined",best:"Full-spectrum healing",why:"The everything blend: tissue repair + collagen + immune modulation + inflammation control.",plain:"The full toolkit: heal tissue, build collagen, calm inflammation, balance your immune system. Four peptides working together.",areas:["Complete tissue repair","Immune system balance","Gut inflammation","Collagen production","Multi-pathway healing"],studies:[{t:"See individual component data",j:"Multiple",y:2020}],seq:"GHK-Cu + KPV + BPC-157 + TB-500",store:"Keep frozen as powder. Refrigerate once mixed."},
  cjcipa:{name:"CJC/Ipamorelin Blend",cat:"Blends",mw:"CJC-1295 + Ipamorelin",best:"Growth hormone, sleep",why:"The gold standard GH stack. CJC triggers GH release, Ipamorelin amplifies it.",plain:"Two peptides that hit different GH switches in your brain. The combo is stronger than either alone.",areas:["Amplified GH release","Better deep sleep","Fat loss","Lean muscle support","Recovery and repair"],studies:[{t:"See individual data",j:"Multiple",y:2010}],seq:"CJC-1295 No DAC + Ipamorelin",store:"Keep frozen as powder. Refrigerate once mixed."},
  tesamipa:{name:"Tesamorelin/Ipamorelin",cat:"Blends",mw:"Tesamorelin + Ipamorelin",best:"Premium GH optimization",why:"The premium stack: FDA-approved Tesamorelin + cleanest GH booster.",plain:"Combines an FDA-approved GH peptide with the most selective GH booster. The premium choice.",areas:["FDA-approved component","Clean GH elevation","Belly fat targeting","Metabolic improvement","Premium GH stack"],studies:[{t:"See individual data",j:"Multiple",y:2015}],seq:"Tesamorelin + Ipamorelin",store:"Keep frozen as powder. Refrigerate once mixed."}
};

// Published / commonly-reported half-life values (educational reference, not dosing advice)
export const HALF_LIVES = {
  bpc157:"~4 hours",tb500:"~2 hours (long tissue retention)",ll37:"~30 minutes",kpv:"Short (~30 min)",
  ta1:"~2 hours",glutathione:"~10 minutes (IV)",ghkcu:"~2 hours",ss31:"~2.5 hours",
  epithalon:"Short — downstream effects last much longer",motsc:"Minutes (effects via gene expression)",
  nad:"~9 hours (systemic)",pinealon:"Short (~hours)",cjcnodac:"~30 minutes",cjcdac:"~8 days",
  ipamorelin:"~2 hours",sermorelin:"~10–20 minutes",tesamorelin:"~35 minutes",
  selank:"Short — effects up to 72h",semax:"Short — effects up to 24h",cerebrolysin:"Variable (protein mix)",
  aod9604:"~30 minutes",semaglutide:"~7 days",tirzepatide:"~5 days",retatrutide:"~6 days",
  pt141:"~2 hours",kisspeptin:"~28 minutes",mt1:"~1 hour",mt2:"~33 minutes",
  wolverine:"4h (BPC) + 2h (TB-500)",glow:"Varies by component",klow:"Varies by component",
  cjcipa:"30min (CJC) + 2h (Ipa)",tesamipa:"35min (Tesa) + 2h (Ipa)"
};

export const FREQ_OPTIONS = [
  {id:"daily",label:"Daily",hours:24},
  {id:"twice-daily",label:"Twice daily",hours:12},
  {id:"eod",label:"Every other day",hours:48},
  {id:"3x-week",label:"3× per week (every 56h)",hours:56},
  {id:"weekly",label:"Weekly",hours:168}
];
